### ISSUE TITLE
problem with already created attribute translation

### ISSUE THREAD

**Issue by Alexandra99** [hyyan/woo-poly-integration#121] opened 2017-02-08 10:21 UTC
Hello i am facing a problem with already created attribute. I created attributes (and translate them) and attribute values (also i translated them). When i create a new product it works fine. But when i try to edit an already created product and i go on attributes from single product to variable product it only displays normally in the default language the attribute name and value and in the translated only the attribute translation and it doesn;t get the value at all. I tried to save them again on default language and then the translated again but with no luck. Am i doing something wrong?

**Comment by Alexandra99** [comment] 2017-02-14 07:09
can anyone please help?

**Comment by Jon007** [comment] 2017-04-01 01:19
Hi, the description of this problem may not be clear enough for people to be able to help.

I just looked at this again as was testing some similar issue, but I don't understand the sentence "...i go on attributes from single product to variable product.."

I can't work out what your exact scenario is so I can't reproduce the problem. 
Typically something like this happens when there is an attribute value which is not translated.

**Comment by Jon007** [comment] 2017-04-29 12:08
closing - Please reraise with clearer description if help still needed.

**Closed by Jon007** 2017-04-29 12:08 UTC
