### ISSUE TITLE
Error Message: The plugin can not function correctly 

### ISSUE THREAD

**Issue by sparlink** [hyyan/woo-poly-integration#35] opened 2016-05-17 10:11 UTC
I have both Polylang (Pro) and Woocommerse installed, but I keep getting an error message at the top of the admin screen: "The plugin can not function correctly , the plugin requires WooCommerce and Polylang plugins".
What is the problem?  I tried reinstall Hyyan plugin, but it didn't work.  I have been using WooCommerse for a few years now, so, reinstalling it is out of question.

At the same time, when creating a duplicate product in the second language, variable product does not work. Variable products become a regular simple product.  Is that because the plugin is not working properly?

Thank you for your help!

**Comment by decarvalhoaa** [comment] 2016-05-17 19:12
Hello,

I'm not using Polylang Pro version and since it is a paid version I can't install it to test it. I'm using however the Polylang free version and don't have that issue. 

Since Hyyan could not support his plugin, I have created a fork and manage to patch a couple of issues. Can I ask you whether you could install my version and see if it works? You can downloaded here [https://github.com/decarvalhoaa/woo-poly-integration/archive/master.zip](url).

**Comment by decarvalhoaa** [comment] 2016-05-17 19:20
Hi again,

I just checked how this plugin checks if woocommerce and polylang are installed.

For polylang, is checking whether the file <install_dir>/wp-content/plugins/**polylang/polylang.php** is an active plugin. Can you check in the <install_dir>/wp-content/plugins/ folder how is polylang pro installed, i.e. is it still creating a directory called **polylang** with a file named the same way with **.php** extension?

**Comment by sparlink** [comment] 2016-05-18 08:30
I checked the plugin folder, and the folder name was polyland_pro, so I changed it to polylang.
After changing this, the plugin was activated!

However, when I tried to create a product in the second language, everything worked except for product variation. Does Polylang free version work better?

**Comment by decarvalhoaa** [comment] 2016-05-18 09:40
I don't recommend changing the folder name. this can create other type of problems with Polylang Pro itself and void support from the author. Instead is best to add the validation to Woo-Poly-Integration plugin in the Plugin.php file, here https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Plugin.php#L88-L91

I don't think the issues with variations are caused by Polylang (either version) but rather some bugs in Woo-Poly-Integration plugin. I have manage to get it working for my needs.

I don't use custom attributes, i.e. attributes that you create in the add product page. I use global attribute, i.e. create the attribute in the Product -> Attribute, translate in both languages before creating the product in any of the languages. 

I'm setting variations this ways and is works reasonably well. The issue is that the default variation is not synced. This means when you update the product on language A, product in language B will get the default unset. To overcome this, I unselected the plugin settings to lock the sync fields (top of my head, don't remember the name of the option) and set the default variation manually on each product just by hitting save variations (don't use update product).

When I have time, I will try to fix the variations issues but don't have a timeline for that yet.

**Comment by sparlink** [comment] 2016-05-22 04:35
Hi Antonio,

Thank you for the instructions. Your methods worked.  It is a pain to
recreate all the variations/attributes for a few hundred existing products,
but I understand how to make it work now.
I hope you can find some time to fix the variations issues in the near
future - I assume there are a lot of people having similar issues.

Thanks a lot!
Meri

**Comment by hyyan** [comment] 2016-07-30 11:26
Fixed now

**Closed by hyyan** 2016-07-30 11:26 UTC
Labels: bug

**Comment by pherdeco** [comment] 2016-10-03 13:52
I still had the issue with version 0.28, because the Polylang Pro plugin that i purchased and installed, is in folder "polylang-pro" and not "polylang_pro".
I used the same trick as decarvalhoaa and added this folder name in the Plugin.php file.

**Comment by decarvalhoaa** [comment] 2016-10-03 17:11
yep! thanks for reporting. I will create a patch for that and push it to a next release #68.

**Comment by pherdeco** [comment] 2016-10-04 06:31
yes this is correct in my installation (Polylang Pro Version 2.0.5)
$find . -name polylang.php
./wp-content/plugins/polylang-pro/polylang.php

**Comment by decarvalhoaa** [comment] 2016-10-04 15:46
thanks

**Comment by pherdeco** [comment] 2016-11-18 08:37
Hello!
there is still a bug in the new version, you wrote "polyland-pro" and not "polylang-pro" as the folder name.

Cheers

**Comment by hyyan** [comment] 2016-11-18 08:39
@pherdeco  thank you for reporting , I will fix this again soon

**Comment by decarvalhoaa** [comment] 2016-11-18 11:46
I just check the master branch for release 0.29 and the polylang detection seems correct, i.e it is checking if plugin polylang-pro/polylang.php is activated. You can cehck it here:

https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Plugin.php#L85-L91

@pherdeco - can you go to this file on your installation and check if you have something different? If not, can you try disabling and activating the Woo-Poly plugin?

**Comment by hyyan** [comment] 2016-11-18 11:48
@decarvalhoaa there is a type `polyland` instead of `polylang`

**Comment by decarvalhoaa** [comment] 2016-11-18 11:51
@hyyan you are right, and I'm going blind - was only looking for the "_" vs "-" (the original problem)

**Comment by hyyan** [comment] 2016-11-18 11:51
@decarvalhoaa kein problem 😄
