### ISSUE TITLE
Variations Duplicates on secondary language product saving/updating

### ISSUE THREAD

**Issue by AmrSubZero** [hyyan/woo-poly-integration#524] opened 2021-01-11 22:48 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Same

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Same

#### What product versions and settings are you using when this issue occurs?
* PHP: **7.4.13**
* WordPress: **5.6**
* WooCommerce: **4.8.0**
* Polylang: **Polylang PRO 2.9.1**
* Hyyan WooCommerce Polylang Integration: **1.4.3**
* Browser: **Google Chrome Version 87.0.4280.88 (64-bit)**
* Polylang with WooCommerce: **Installed / Activated**

#### Steps to Reproduce
1. Create a variable product in two languages and create variations for sizes _e.g: XL-M-L-S_ on the original language product.
2. Navigate to the product in the secondary language and click **Update**.

#### What I Expected
I expected the basic behavior like seeing only the exact variations and count of variations i've set to the original language product.

#### What Happened Instead
Everytime i navigate to the product in secondary language and hit **save/update** i see the **variations duplicating with same sku**.

and it keeps duplicating as i click **update**. with same **sku** for all variations i have.

**_NOTE :_** if i'm on the original language product and clicking update it doesn't. it only duplicates varations on the other language product. notice that i have **Polylang with WooCommerce** installed & activated.

**_NOTE :_** i have **Product Size** unchecked/disabled in Polylang **Custom post types and Taxonomies** settings. no need to translate sizes to other languages.

**_UPDATE :_** i have disabled **Polylang with WooCommerce** plugin and **removed/re-created** the products again to avoid if there's a database conflict. but the problem **still persist**.

![image](https://user-images.githubusercontent.com/5399778/104246940-871f2380-546f-11eb-8e3c-6d58de2b97cc.png)

## WordPress Environment

<details>

```
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: ar
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.13
PHP Version: 7.4.13
PHP Post Max Size: 1 GB
PHP Time Limit: 5000
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 18.57MB
Database Data Size: 13.75MB
Database Index Size: 4.82MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.12MB + Index: 0.06MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.07MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_eum_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_cms_nav_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Data: 0.11MB + Index: 0.11MB + Engine MyISAM
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_mo_files_domains: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_icl_node: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Data: 5.94MB + Index: 3.31MB + Engine MyISAM
wp_icl_string_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_packages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_pages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_positions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Data: 1.01MB + Index: 0.43MB + Engine MyISAM
wp_icl_string_urls: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translations: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 3.66MB + Index: 0.12MB + Engine MyISAM
wp_postmeta: Data: 1.99MB + Index: 0.27MB + Engine MyISAM
wp_posts: Data: 0.36MB + Index: 0.06MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_soo_wishlists: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_soo_wishlists_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

page: 32
polylang_mo: 2
product: 25
product_variation: 7

### Security ###

Secure connection (HTTPS): ❌
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: EGP (EGP)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7610 - /shop/
Cart: #7623 - /cart/
Checkout: #7625 - /checkout/
My account: #7620 - /my-account/
Terms and conditions: #361 - /en/terms-conditions/
```

</details>

**Comment by Jon007** [comment] 2021-02-02 23:36
duplicate of #430 - which had been fixed but reoccurred - now fixed again in source

**Closed** 2021-02-02 23:35 UTC
