### ISSUE TITLE
"WooCommerce PayPal Express Checkout Gateway" plugin introduces admin incompatibility on product images

### ISSUE THREAD

**Issue by Skinperforator** [hyyan/woo-poly-integration#293] opened 2018-01-09 15:52 UTC
Hi,
sorry I'm not able at the moment to try and recreate the problem on a fresh install, so I can only describe the problem from my running shop.

I'm running:
PHP 5.6.3
Wordpress 4.9.1
WooCommerce 3.2.6
Polylang 2.2.8 (not pro)
Hyyan WooCommerce Polylang Integration 1.0.4
Chrome 63.0.3239.132 x64

The problem is, that when I have the plugin activated, I can't add product images anymore (neither featured images for posts). Upload works fine, but when I select an image and hit save the thumbnail doesn't appear. When I try to add it again there seems to be just a blank grey image with no meta data selected. When I deaktivate the plugin it works normal. 
Any idea what could cause this?

Thanks in advance!

**Comment by osoibol** [comment] 2018-01-09 16:14
I have exactly the same problem

Wordpress 4.9.1
WooCommerce 3.2.6
Polylang 2.2.8 (Not Pro)
Hyyan WooCommerce Polylang Integration 1.0.4
+Other plugins I deactivated to make sure it wasn't their fault.

Tried on Opera & Firefox so I believe is a global problem and not a browser related one.

**Comment by Jon007** [comment] 2018-01-09 16:30
This functionality works fine normally and is not affected by this plugin. I just tried the update to Polylang 2.2.8 and it still works, both in a minimal storefront setup and in full setups.

You are most likely seeing a compatibility problem with your theme or other plugin. 
A clue here is in some earlier comment that featured images for posts don't work either "(neither featured images for posts)".

Please try it with Storefront and with other plugins deactivated (only woocommerce, polylang, woopoly turned on). You should find that works, so then you can activate other plugins until you find which one is having the conflict.

Also I suggest that the Polylang settings:
- Languages, Settings, Media  should not be activated, otherwise you need different images for each language which should be problematic
- Languages, Settings, Synchronisation, Featured image should be turned on to synchronize between translations.

In any case post Featured Image synchronisation is provided by Polylang, it is not a special feature of woocommerce or this plugin so it should be closed here...
also duplicate of #288

**Comment by Skinperforator** [comment] 2018-01-09 16:39
Strange then that it works when WooPoly is deactivated, isnt it?
I also use Storefront and until the recent update of WooCommerce and Polylang it worked fine.

**Comment by Jon007** [comment] 2018-01-09 17:27
Does anything come up when running in debug?

well as I reconfirmed it works with:
Wordpress 4.9.1
WooCommerce 3.2.6
Polylang 2.2.8 (not pro)
Hyyan WooCommerce Polylang Integration 1.0.4
the only other difference I can see is you are running PHP5.6 whereas PHP7 is recommended by WooCommerce (and everything else).

If you were able to confirm that it works for you on an earlier version of Polylang that would be interesting.

**Comment by osoibol** [comment] 2018-01-10 08:26
It isn't working for me.
"Create Product" --> "Product Image" shows me the wrong button, instead of saying "Set Product Image" it says"Set Featured Image" and clicking at the button closes the window prompt but doesn't loads the image.

If I use WooCommerce 3.2.6 and Polylang 2.2.8 it works, but if I activate Hyyan WooCommerce Polylang Integration 1.0.4 it stops working.

**Comment by Jon007** [comment] 2018-01-10 08:42
@osoibol have you tried using Storefront and disabling all other plugins apart from WooCommerce 3.2.6, Polylang 2.2.8 and Hyyan WooCommerce Polylang Integration 1.0.4 ?

Post should say Set Featured Image
Product should say Set Product Image, unless WooCommerce is deactivated or something is interfering with it.  Eg some plugin or theme modification is taking over the 'Product' post type and causing the woocommerce rendering not to be activated...

This plugin does not do ANY action related to the images, this is handled by woocommerce and polylang already.

I can't reproduce this on 
- WooCommerce 3.2.6 
- Polylang 2.2.8, 
- Hyyan WooCommerce Polylang Integration 1.0.4 -
- Storefront 2.2.5
or any other version for that matter.

**Comment by mathis89** [comment] 2018-01-10 10:25
I have the same problem, that I can't add/delete images from products and posts, but I just figured out, that in my case the combination with the plugin "WooCommerce PayPal Express Checkout Gateway" is the problem. When I deactivate the PayPal plugin everything is working fine. Perhaps this could be helpful for others and a fix in the future would be great. :-)

- Wordpress 4.9.1
- Polylang 2.2.8
- Hyyan WooCommerce Polylang Integration 1.0.4
- WooCommerce 3.2.6

**Comment by Jon007** [comment] 2018-01-10 11:02
@mathis89 great - perhaps you can report it to the authors of "WooCommerce PayPal Express Checkout Gateway" too.

While you are there, what's the benefit of the "WooCommerce PayPal Express Checkout Gateway" rather than the built in WooCommerce Paypal gateway?  (which is more commonly used with this plugin and tested).

It's likely that the WooCommerce PayPal Express Checkout Gateway extends the product screen to add configuration items for Paypal recurring payments or other Paypal function in a way that has a filter priority conflict with other plugins, in which case a tweak of the priority level could fix it.

**Comment by mathis89** [comment] 2018-01-10 13:29
@Jon007 I'm sorry but I can't tell you the benefits of the "WooCommerce PayPal Express Checkout Gateway" plugin. My shop is still under development and I guess that I only installed the plugin because WooCommerce suggested it. So in my case I won't use the PayPal plugin anymore, because I need the functionality of the "Hyyan WooCommerce Polylang Integration" plugin.

**Comment by Skinperforator** [comment] 2018-01-10 13:36
That seems to be it. In my case after deactivating Paypal Express it also works. Thanks!

**Comment by Jon007** [comment] 2018-01-10 13:51
Ok @Skinperforator Skinperforator, in this case I will change the title of this issue.

Conclusion:
An incompatibility potentially introduced in a recent version of:
https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/
is affecting ability to edit product images when this plugin is also activated.

Workaround:
- deactivate WooCommerce PayPal Express Checkout Gateway plugin 
- use the Paypal gateway which is built into the WooCommerce plugin

There are also other alternatives such as the AngellEye plugin:
https://wordpress.org/plugins/paypal-for-woocommerce/
depending on what is the additional functionality being offered by the WooCommerce PayPal Express Checkout Gateway which you would like to use.

Ideally, someone using the WooCommerce PayPal Express Checkout Gateway would be able to debug which filter is causing the problem and raise filter priority alterations to both of these components.

**Comment by osoibol** [comment] 2018-01-10 16:02
yep, I can confirm WooCommerce PayPal Express Checkout Gateway plugin is the guilty plugin! thanks!

**Comment by Jon007** [comment] 2019-05-25 21:09
I will close this issue as it is outdated and this particular paypal plugin is not in scope of this plugin (and easily replaceable with many other paypal plugins available or native woocommerce paypal which works fine).

if it is this plugin:
https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/
I tested the latest version and could not reproduce this issue in current versions.

**Closed by Jon007** 2019-05-25 21:09 UTC
