### ISSUE TITLE
Wrong product language in Woocommerce cart and checkout

### ISSUE THREAD

**Issue by albert0346** [hyyan/woo-poly-integration#256] opened 2017-11-01 18:37 UTC
Hi,

I have

. PHP 5.6.30-0+deb8u1
. Wordpress 4.8.3
. Woocommerce 3.2.2
. Polylang 2.2.4
. Hyyan WooCommerce Polylang Integration 1.0.3
. Firefox 56.0.2

I reproduced the following error also on Storefront (I use Boutique)
I reproduced this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration.

I have a site in German and English, with German as the default language. When I enter the shop, select the English language with the Polylang language switcher, select then the English translation of a variable product and put it into the cart and go with the cursor over the cart icon it shows the product in German language. But when I use the link “View Basket” it shows it in English language. But when I then use Proceed to Checkout I get the product in German language.

This is very confusing to me. Please help. Thanks a lot in advance.

Albert

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Juan-Orjuela** [comment] 2017-11-01 19:20
Hi! I'm having the same issue.

**Comment by ylt04** [comment] 2017-11-01 23:44
Yes, I am also having similar issue in cart page and checkout page.

**Comment by hyyan** [comment] 2017-11-02 08:34
Please install the plugin from the master branch , it solved there , the new version has not been released yet

**Comment by albert0346** [comment] 2017-11-02 16:21
hyyan, THANKS A LOT! IT WORKS WITH THE MASTER BRANCH!!

**Comment by Skinperforator** [comment] 2017-11-02 16:27
Is there a way to update? I don't want to loose my settings.
Sorry, if I did something wrong. When I uploaded the zip from the master, there was another copy of the plugin and it couldn't be activated because it threw a fatal error.

**Comment by albert0346** [comment] 2017-11-02 16:43
There isn't so much data in the plugin which you would loose. You can go through it very fast after it is installed.

I deleted the plugin and uploaded the master version. And now everything is fine.

**Comment by Jon007** [comment] 2017-11-06 10:08
closing as solved in master and duplicate of #240

**Closed by Jon007** 2017-11-06 10:08 UTC

**Comment by sievlyyin** [comment] 2018-04-26 04:44
I have downloaded and installed THE MASTER BRANCH!! but it seems doesn't support the new version of WooCommerce.
My old WooCommerce Version 3.1.2 works fine, but I want to update my WooCommerce to the latest version 3.3.5 without getting the above issue. how could I able to do that?

**Comment by Jon007** [comment] 2018-04-26 05:27
See #319 and related pull request #329
You need the new Ajax.php which is not yet merged,

v1.0.4 fixed this for woo 3.2 but woocommerce made more breaking changes in v3.3

**Comment by sievlyyin** [comment] 2018-04-27 04:36
Thank you @Jon007 for your valuable help.
But the problem has not been fixed for me yet.
After read and followed from the articles above  #319 and #329 
I have tested with:
- WooCommerce 3.2.0
- Hyyan WooCommerce Polylang Integration 1.0.4
- Polylang 2.2.7
And Ajax
add_filter('woocommerce_ajax_get_endpoint', 'pll_woocommerce_ajax_get_endpoint', 10, 2);
    public function pll_woocommerce_ajax_get_endpoint($result, $request){
        return esc_url_raw( add_query_arg( 'wc-ajax', $request, remove_query_arg( array( 'remove_item', 'add-to-cart', 'added-to-cart' ) ) ) );        
    }
Is there something wrong? 
Absolutely I am a beginner. If you have some more info, please drop it.
Again thanks for your help.

**Comment by Jon007** [comment] 2018-04-27 05:31
Well for a start don’t use woocommerce 3.2.0
3.2.0 was patched only 2 days later by 3.2.1 with 43 commits (Oct 11, Oct 13) and 3.2.2 with 81 commits on October 31.  3.2.3 was then released only 2 days after 3.2.2, followed quickly by 3.2.4 and then 3.2.5...

**Comment by Jon007** [comment] 2018-04-27 05:40
3.1.2 and 3.2.5 should work with v1.0.4 of this plugin
3.3.5 may work with this plugin with the new Ajax.php file and other changes in master branch but this is not fully tested and released.

To give you an idea, I am not a beginner and I still use 3.1.2
