### ISSUE TITLE
Problem with mini cart after cart is udated

### ISSUE THREAD

**Issue by Musilda** [hyyan/woo-poly-integration#278] opened 2017-12-07 10:45 UTC
I have problem with Cookie is not defined on https://medianest.net

Polylang 2.2.7
WooCommerce 3.2.5
WordPress 4.9.1

Also is problem, when cart is updating and language is EN, after refreshing, buttons in cart are in Czech and in minicart are links leads to Czech versions of cart and checkout. But this may be will be Avada issue.

**Comment by Jon007** [comment] 2017-12-08 02:57
please note version 1.0.3 is only compatible with WooCommerce 3.0 and 3.1.
WooCommerce 3.2 has changed the ajax handling so the mini-cart and order review sections do not pick up language.
There are fixes for this in the master branch which are pending release, you are welcome to try them.
see also #256 and #274 - this is duplicate of #274

**Closed by Jon007** 2017-12-08 02:57 UTC
