### ISSUE TITLE
 Cannot translate cart checkout myaccount Woocommerce Polylang

### ISSUE THREAD

**Issue by kmammasis** [hyyan/woo-poly-integration#447] opened 2019-07-30 15:35 UTC
Hello,

I am having problems in translating my woocommerce cart, checkout and account pages. I am using polylang in conjuction with Hyyan WooCommerce Polylang Integration. Although I have created double pages, one for each language, for products, tags, categories etc., when it comes to translating the content of the cart page for example, it does not reflect any changes in ,y language. I then installed loco translate and performed most steps shown in the forum that relate to the correct usage of this plugin. In Dashboard–>Loco–>Plugins–>Woocommerce I find all required translations in the .po file, however these are not loaded although they are in the correct folder. I have tried many different things and followed the steps as described in: https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started

It is difficult to report all my actions so far but honestly I have tried many different things but still cart, checkout and myaccount pages for woocommerce remain in English

However nothing seems to work for me. http://indi.ofdreamsandknowledge.gr/wordpress/el/checkout-el/

I would appreciate if someone sheds light on this one
Thank you very much
Konstantinos

![s](https://user-images.githubusercontent.com/53486232/62143327-7c62e400-b2f8-11e9-914a-1e7326bd8c17.jpg)

**Comment by Jon007** [comment] 2019-07-30 18:35
Hi @kmammasis 

you have not provided the information requested when raising a new issue, this is very important, especially if you expect people to spend their spare time helping you for free.

What does this page look like in edit mode?
Are there any warnings in admin mode?

It is important to test with a standard theme ie Storefront to rule out any problems which could be introduced by the theme and custom woocommerce templates.

Similarly it is also important to know what other plugins are enabled and if you have tried turning off other plugins.
as well as which version of this plugin.
I can see you have created the products as translated pages, but the entire woocommerce front end part seems to be running in English
http://indi.ofdreamsandknowledge.gr/wordpress/el/%CF%80%CF%81%CE%BF%CF%8A%CF%8C%CE%BD/bio_pomegranate_el/
not just the cart page, all the standard texts on the product page like "Description" would normally be translated.

I'll have to close this as there is not enough information provided to investigate the issue, please re-raise adding the information requested,

**Closed** 2019-07-30 18:36 UTC

**Comment by kmammasis** [comment] 2019-07-30 19:51
Thank you for your help and apologies if I wasted your time. I did my best to describe the problem. Obviously, it was not enough. 

Kind Regards,
Konstantinos

**Comment by Jon007** [comment] 2019-07-30 21:41
@kmammasis hi, 
perhaps you did not understand, your explanation is ok, the problem is you did not answer the questions asked when raising an issue: when you raise a new issue you need to answer the questions and fill in the status report.  when you visit:
https://github.com/hyyan/woo-poly-integration/issues/new

there is this form to report details and you need to answer these questions:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 


#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected



#### What Happened Instead


## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment] 2019-07-31 22:51
@kmammasis 
this really looks as if the woocommerce greek translation files may not have downloaded properly, try switching languages in the admin, when you run admin views in greek, do all the woocommerce menus and options appear in Greed?
