### ISSUE TITLE
Duplicate product not working

### ISSUE THREAD

**Issue by MU85** [hyyan/woo-poly-integration#149] opened 2017-04-30 13:11 UTC
Hi,
I love this plugin, but I just realized that whenever I have it activated, the duplicate function I can normally choose in the product overview under each product (next to edit, quick edit, trash and view) disappears.
I can see it again when I deactivate Woo-Poly-Integration. How can I duplicate a product, while having this plugin active?
Thanks a lot,
Michaela

**Comment by Jon007** [comment] 2017-04-30 14:13
Hi there,
Duplicate is specifically not there on Variation products, it is implemented ok on standard products.

Note that duplicate should be used in main language to create a duplicate of the product, it doesn't currently duplicate the translations.

**Comment by MU85** [comment] 2017-04-30 15:36
Hi,

So there is no way for me to duplicate a variation product? I have to set up all the variations manually?

Cheers,

Michaela

 

Von: Jonathan Moore [mailto:notifications@github.com] 
Gesendet: 30 April, 2017 16:14
An: hyyan/woo-poly-integration
Cc: MU85; Author
Betreff: Re: [hyyan/woo-poly-integration] Duplicate product not working (#149)

 

Hi there,
Duplicate is specifically not there on Variation products, it is implemented ok on standard products.

Note that duplicate should be used in main language to create a duplicate of the product, it doesn't currently duplicate the translations.

**Comment by Jon007** [comment] 2017-04-30 15:58
Well there are two possibilities, if you have a test system to experiment on:

1. deactivate woo-poly-integration, duplicate, and then reactivate. I haven't tried it

2. comment out these lines at the top of:  /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Duplicator.php
//        add_action('woocommerce_duplicate_product_capability', array(
//            $this, 'disableDuplicateForVariables',
//        ));

Now, the Duplicate link will be available for variations, when you first duplicate the Product will appear as a Simple product, just change it to Variation product, press Save and the variations will appear.

Warning:  I didn't write this code, I just experimented just now to see what would happen, I can't guarantee there are no side effects, this code was obviously put there for a reason, and I only tested on my local with WooCommerce 3.0.5 and the compatibility beta code for this plugin.  
.. But it seems to work..

**Comment by MU85** [comment] 2017-05-01 12:51
Hi Jonathan,

Thanks a lot for the suggestions. I thought about the first option as well, but I’d prefer the second one to be honest. Unfortunately I’m not very experienced with php (though I can do some basic stuff). Is it possible to include that code in my functions.php file for my child theme, or does it have to be this duplicator file you mention? Also, what exactly do you mean by “comment out”? I can’t just copy the code you gave me below?  ( I guess the // are in the way; can I just remove them?)

Thanks a lot for your help,

Michaela

 

Von: Jonathan Moore [mailto:notifications@github.com] 
Gesendet: 30 April, 2017 17:58
An: hyyan/woo-poly-integration
Cc: MU85; Author
Betreff: Re: [hyyan/woo-poly-integration] Duplicate product not working (#149)

 

Well there are two possibilities, if you have a test system to experiment on:

1.     deactivate woo-poly-integration, duplicate, and then reactivate. I haven't tried it

2.     comment out these lines at the top of: /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Duplicator.php
// add_action('woocommerce_duplicate_product_capability', array(
// $this, 'disableDuplicateForVariables',
// ));

Now, the Duplicate link will be available for variations, when you first duplicate the Product will appear as a Simple product, just change it to Variation product, press Save and the variations will appear.

Warning: I didn't write this code, I just experimented just now to see what would happen, I can't guarantee there are no side effects, this code was obviously put there for a reason, and I only tested on my local with WooCommerce 3.0.5 and the compatibility beta code for this plugin.
.. But it seems to work..

**Comment by Jon007** [comment] 2017-05-01 13:00
The "//" is the comment symbol, placing // in front of those lines in duplicator.php as I indicated causes those lines to be removed from execution and treated as a comment. Hence adding the // is known as "commenting out" the code.
This is less destructive than deleting the lines since you can easily remove the // again.

Of course if you aren't really sure about what you are doing I cannot really advise you to do it.
I am interested to know if it works for you though..  but if you test please do on test system not directly on your production system.

Please only reply in GitHub rather than by email, or at least don't include the history in email: your email is added to the history in GitHub and re-attaching all the history to the history only makes it harder to read...

**Comment by MU85** [comment] 2017-05-04 19:25
Hi Jonathan,
I commented out the code as you suggested, but unfortunately it did not work out. This is how I did it:
1. copied the file /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Duplicator.php
2. uploaded the downloaded file directly into my child theme
3. commented out the three lines as suggested by you
Was there anything wrong about this procedure?

I also tested your first option (turn off the plugin, duplicate, and then reactivate). That one works, but it's anything from a pretty and clean workflow, so I'd love to get the code altered to fix this issue. 

Any other ideas?

**Comment by Jon007** [comment] 2017-05-04 23:57
No, no, you would need to edit 
/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Duplicator.php
directly, save it at that location.
Copying such files to your theme can only break things.

Also, next time there is a problem you need to be a whole lot more specific than "it did not work out", I'm just answering on a volunteer basis, so please don't expect me to spend extra time working out what you mean.

I have some success in local development with improving the product attribute handling, I estimate I'll get an improved release candidate out next week.

**Comment by Jon007** [comment] 2017-05-05 17:29
fixed in dev branch:
https://github.com/Jon007/woo-poly-integration/tree/taxnomy-and-product-attributes-enhance
This needs a little more work and testing before including in release candidate.

Note:  if you duplicate a variation which is not in the site language, a lot of the attributes may not be editable (depending on your synchronisation and fields locker settings).
Since variations are synchronized from base language at the moment, that means to edit, you create a translation in the base language and edit there.

**Comment by MU85** [comment] 2017-05-05 23:59
Hi Jonathan,
if I edit the original file, then everytime I update it my adjusted code is gone. That's why I tried it the other way.
Could you please specify what the link you gave me is for? Is that a Hyyan WooCommerce Polylang extension/add on or an adjusted version?
By the way: I also realized that I have no possibility to edit the variations in my second language while I have the Hyyan WooCommerce Polylang plugin activated. Is that another bug?
Thanks for your help, really appreciated.
Michaela

**Comment by Jon007** [comment] 2017-05-06 01:23
>if I edit the original file, then everytime I update it my adjusted code is gone
no it won't be gone it will be included in the next release

>Could you please specify what the link you gave me is for? 
These are branches where we are preparing the next releases

>I also realized that I have no possibility to edit the variations in my second language while I have the Hyyan WooCommerce Polylang plugin activated. Is that another bug?
This is kind of the point of the tool, to keep the variations in sync.  You edit in one language, normally the main site language, and the information is updated in all translations.

A lot of the fields can also be unselected for synchronisation in Settings, WooPoly in which case they become editable in the other languages.

**Comment by hyyan** [comment] 2017-05-13 22:37
@Jon007 , @MU85  Variation Product can not be duplicated in this simple form, commenting this code will make you lose the linked variation products.  This needs a robust solution which is not in my Todo list 
for this plugin right now.

@MU85  you do not need to edit Variations, everything is synced, so edit the product in your main language

**Comment by Jon007** [comment] 2017-05-20 06:42
I retested this successfully in the attributes dev branch which I've now moved to:
https://github.com/hyyan/woo-poly-integration/tree/product-taxnomy-attributes-dev

If it works fine and could save people a LOT of time with manually setting up variations, 
let's leave it enabled and I'll fix any specific bug report that arises.

**Closed** 2017-06-01 17:47 UTC
Labels: enhancement
