### ISSUE TITLE
Manual order creation - Payment method translation problem

### ISSUE THREAD

**Issue by fkoomek** [hyyan/woo-poly-integration#393] opened 2019-02-04 13:00 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
YES

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
YES

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1.26
* WordPress:  5.03
* WooCommerce:  3.5.4
* Polylang: [state if using Polylang PRO] 2.5.1 (free)
* Hyyan WooCommerce Polylang Integration: 1.2.0 
* Browser: Firefox, Chrome

#### Steps to Reproduce
1. Set up Polylang with at least 2 languages.
2. Click Add order in Woocommerce orders tab.
4. Choose a payment method which has translation also in other languages, not for example PayPal (but COD or Bank Transfer...). Fill your email to the order.
5. Add some product to the order and set the language of the order other than the default one.
6. Click Create order

#### What I Expected
In the email, which customer receives the payment method title is translated.

#### What Happened Instead
The title of the payment method still stays in the default language although everything else in the email is translated correctly.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: http://testing.liberlapidum.com
Site URL: http://testing.liberlapidum.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.26 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: fits_
MaxMind GeoIP Database: ✔
Total Database Size: 2.88MB
Database Data Size: 2.04MB
Database Index Size: 0.84MB
fits_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
fits_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
fits_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
fits_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
fits_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
fits_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
fits_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
fits_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
fits_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
fits_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
fits_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
fits_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
fits_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
fits_woocommerce_log: Data: 0.02MB + Index: 0.02MB
fits_commentmeta: Data: 0.02MB + Index: 0.03MB
fits_comments: Data: 0.02MB + Index: 0.08MB
fits_links: Data: 0.02MB + Index: 0.02MB
fits_options: Data: 1.50MB + Index: 0.02MB
fits_postmeta: Data: 0.02MB + Index: 0.03MB
fits_posts: Data: 0.02MB + Index: 0.06MB
fits_termmeta: Data: 0.02MB + Index: 0.03MB
fits_terms: Data: 0.02MB + Index: 0.03MB
fits_term_relationships: Data: 0.02MB + Index: 0.02MB
fits_term_taxonomy: Data: 0.02MB + Index: 0.03MB
fits_usermeta: Data: 0.02MB + Index: 0.03MB
fits_users: Data: 0.02MB + Index: 0.05MB
fits_wc_download_log: Data: 0.02MB + Index: 0.03MB
fits_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 4
customize_changeset: 1
nav_menu_item: 4
page: 6
polylang_mo: 2
post: 2
product: 2
revision: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Polylang: by Frédéric Demarle – 2.5.1
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /cs/shop/
Cart: #13 - /cs/cart/
Checkout: #14 - /cs/checkout/
My account: #15 - /cs/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Jon007** [comment] 2019-03-10 07:00
this should normally work, if the String translations are set, normally at:
/wp-admin/admin.php?page=mlang_strings&s&group=WooCommerce+Payment+Gateways&paged=1

**Comment by fkoomek** [comment] 2019-03-12 17:34
Hello. 
When an order is created from frontend in the Czech language, which is my default language, the payment method title in the email received by the customer is translated correctly. But when I go to admin to change the payment method ( for example in case customer would like to change that) and resend an email to the customer, the payment method appears in English - the second language. Everything else is still translated.
Also as I wrote earlier, when the order language is changed from English to Czech and email is resent, the payment method is not translated.

**Comment by fkoomek** [comment] 2019-03-12 17:34
Strings are translated correctly

**Comment by fkoomek** [comment] 2019-03-14 18:28
I found out that the payment method title is just determined by the language of the WP environment.

**Comment by Jon007** [comment] 2019-03-14 22:36
No, if it is determined by the language of the wp environment then it is translated, or at least translatable.
The plugin changes the language when sending the emails, however by default it only reloads the translation text domains for woocommerce and woo-poly.
So if another plugin is adding content for its own text domain then you would need to reload that text domain too.  Here is some sample code for that:

```
/*
 * when switching language for order email, unload these additional text domains
 */
function ii_unload_email_textdomains() {
	unload_textdomain( 'ii-plugin' );
	unload_textdomain( 'woo-advanced-shipment-tracking' );
}

add_action( 'woo-poly.Emails.switchLanguage', 'ii_unload_email_textdomains' );
/*
 * when switching language for order email, reload these additional text domains
 */
function ii_load_email_textdomains() {
	ii_plugin::load_textdomain();
	global $WC_advanced_Shipment_Tracking;
	if ( $WC_advanced_Shipment_Tracking ) {
		$WC_advanced_Shipment_Tracking->wst_load_textdomain();
	}
}
add_action( 'woo-poly.Emails.afterSwitchLanguage', 'ii_load_email_textdomains' );
```

However that does not seem to be your case, and if you are using the built in payment methods like bank transfer, this is normally handled by the polylang strings translation table here:
/wp-admin/admin.php?page=mlang_strings&s&group=WooCommerce+Payment+Gateways&paged=1

if you cant find the string here, then maybe you have not tried customising the strings in:
/wp-admin/admin.php?page=wc-settings&tab=checkout&section=bacs

So either set a string here and translate it in the string translation table, or check the plugin translations using Loco Translate.

Do check the wiki help information here and elsewhere to understand this better:
https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview

**Comment by fkoomek** [comment] 2019-03-15 13:39
Thank you for your response.
Well, I meant that the method title is always determined by WP environment, no matter in what language is an order. So, for example, when I create order in Czech language and WP environment is in English, the email sent to the customer is all in Czech expect for the payment title. 
All strings are translated correctly in polylang as well as in Loco. 
The only solution which I see now is to change the language of Wordpress to Czech when I create order in the Czech language. Only this way the payment method title is translated.

**Comment by Jon007** [comment] 2019-03-15 14:33
What I am telling you is that I have the payment method translating into several languages correctly in the emails, including the bank transfer for example, so if the system is configured correctly this is quite possible to do.

**Comment by fkoomek** [comment] 2019-03-15 14:45
Ok, so you weren't actually able to reproduce that "bug" right? And there is something wrong set in my system.

**Comment by Jon007** [comment] 2019-03-16 09:27
Hi yes, I can't tell what your settings are and this is a free plugin with no paid support people to replicate your issue, but it just so happens that I did a complete review of emails in 3 languages for another site so I can confirm that the payment type translations should work if you follow carefully the notes above.

I also checked in a change related to email subject and title translations since the default strings had changed in woocommerce 3.5+, this broke the default translations which for some reason had been hardcoded into this plugin:
https://github.com/hyyan/woo-poly-integration/issues/401

**Closed by Jon007** 2019-03-16 09:27 UTC

**Comment by fkoomek** [comment] 2019-03-16 10:45
I understand, thank you for your help.
