### ISSUE TITLE
Product edit page always shows simple product as the set type, even though it's not.

### ISSUE THREAD

**Issue by CultureInspired** [hyyan/woo-poly-integration#510] opened 2020-09-03 19:42 UTC
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3
* WordPress: 5.5.1
* WooCommerce: 4.3.0 or 4.4.1
* Polylang: [state if using Polylang PRO] No
* Hyyan WooCommerce Polylang Integration: Yes
* Browser: Chrome

#### Steps to Reproduce
1. Upgrade WP to 5.5.1
1. Visit the edit screen for a WooCommerce product
1. Note it always shows the product type set to "simple", even when changed and saved.

#### What I Expected

Product type shown as selected on the edit screen to change to whatever you choose after saving.

#### What Happened Instead

Product type actually changes, but always displays the "simple" product type as selected in the edit screen no matter what. The product type change is actually applied but is just incorrectly displayed on the edit product screen.

WP 5.5.1 + WC 4.4.1 = problem occurs.
WP 5.5.1 + WC 4.3.0 = problem occurs.

WP 5.4.2 + WC 4.4.1 = problem is gone.
WP 5.4.2 + WC 4.3.0 = problem is gone.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by janis-ps** [comment] 2020-09-04 13:47
I have debugged this, and found that this is caused by bad jQuery usage in this plugin. It is most likely triggered by WordPress finally upgrading their jQuery version.

https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Product/Meta.php#L804

The linked code inject some JS to change the select input value, but does so in a way that is very unconventional. It adds and removes the "selected" attribute from the option elements. I had to take a moment to understand what's happening there. 😄 

```php
                $code = sprintf(
                    '// <![CDATA[ %1$s'
                    . ' addLoadEvent(function () { %1$s'
                    . '  jQuery("#product-type option")'
                    . '     .removeAttr("selected");%1$s'
                    . '  jQuery("#product-type option[value=\"%2$s\"]")'
                    . '         .attr("selected", "selected");%1$s'
                    . '})'
                    . '// ]]>', PHP_EOL, $type[0]
                );
```

Here's a more conventional (and working) way of doing this:

```php
$code = sprintf('addLoadEvent(function () { jQuery("#product-type").val(%s); });', json_encode($type[0]));
```

**Comment by CultureInspired** [comment] 2020-09-04 13:54
Nice find! I had forgot to test using the "Enable jQuery Migrate Helper" plugin during my troubleshooting. I did this morning and it did seem to fix the selection but shows this warning "jQuery.fn.attr('selected') might use property instead of attribute".

How are updates for this plugin being handled now? I see there hasn't been a new release in a year, will this error and your solution change this or do I have to apply the fix to the code locally in my installations by modifying the plugin?

**Comment by janis-ps** [comment] 2020-09-04 14:02
I'm not sure what the situation here is. The README says they're looking for maintainers, so we're looking into moving away from this plugin. Short-term, I'm just applying this fix locally.

**Comment by CultureInspired** [comment] 2020-09-04 14:06
Same, I am going to schedule replacing this plugin with the official Polylang WooCommerce plugin. Thanks for the fix though! Prior to your fix my only solution was to stay off WP 5.5 for now.

**Comment by TomManillion** [comment] 2020-09-05 04:30
Thanks for this solution, although I seem to be experiencing a weird thing happening at the frontend now. So I have a product which is a ticket, being a variable product you can choose between a 'standard' and a 'VIP' ticket.

When you click the VIP ticket, for a few seconds the price of the standard ticket shows up. Only the price, the image and description are of the VIP ticket. Any idea what could be the problem here?

Thanks in advance.

**Comment by janis-ps** [comment] 2020-09-07 07:58
> 
> 
> Thanks for this solution, although I seem to be experiencing a weird thing happening at the frontend now. So I have a product which is a ticket, being a variable product you can choose between a 'standard' and a 'VIP' ticket.
> 
> When you click the VIP ticket, for a few seconds the price of the standard ticket shows up. Only the price, the image and description are of the VIP ticket. Any idea what could be the problem here?
> 
> Thanks in advance.

Unrelated to what's being discussed here.

**Comment by TomManillion** [comment] 2020-09-07 08:31
> > Thanks for this solution, although I seem to be experiencing a weird thing happening at the frontend now. So I have a product which is a ticket, being a variable product you can choose between a 'standard' and a 'VIP' ticket.
> > When you click the VIP ticket, for a few seconds the price of the standard ticket shows up. Only the price, the image and description are of the VIP ticket. Any idea what could be the problem here?
> > Thanks in advance.
> 
> Unrelated to what's being discussed here.

I don't see how it is unrelated, as I am explaining what I am experiencing after implementing the 'solution' you provided.

**Comment by CultureInspired** [comment] 2020-09-07 13:06
That's a secondary issue you're experiencing, I don't have any issues with the frontend. You probably need to add legacy jQuery support to your installation. In short, the solution is a solution and not a "solution".

**Comment by Tii** [comment] 2020-09-07 16:29
> I have debugged this, and found that this is caused by bad jQuery usage in this plugin. It is most likely triggered by WordPress finally upgrading their jQuery version.
> 
> https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Product/Meta.php#L804
> 
> The linked code inject some JS to change the select input value, but does so in a way that is very unconventional. It adds and removes the "selected" attribute from the option elements. I had to take a moment to understand what's happening there. 😄
> 
> ```
>                 $code = sprintf(
>                     '// <![CDATA[ %1$s'
>                     . ' addLoadEvent(function () { %1$s'
>                     . '  jQuery("#product-type option")'
>                     . '     .removeAttr("selected");%1$s'
>                     . '  jQuery("#product-type option[value=\"%2$s\"]")'
>                     . '         .attr("selected", "selected");%1$s'
>                     . '})'
>                     . '// ]]>', PHP_EOL, $type[0]
>                 );
> ```
> 
> Here's a more conventional (and working) way of doing this:
> 
> ```
> $code = sprintf('addLoadEvent(function () { jQuery("#product-type").val(%s); });', json_encode($type[0]));
> ```

great fix, thank you !

**Comment by colyz93** [comment] 2020-09-16 14:01
Great problem solved, thank you
unfortunately some products have stock but in frontend out of stock so i deleted and republished them

**Comment by colyz93** [comment] 2020-09-16 14:26
another problem updating old products turn them out of stock even when they have stock

**Comment by Xukyo** [comment] 2020-10-22 12:17
@janis-ps Thanks a lot your solution worked for me. 
Any news on eventual plugin correction?

**Comment by hyyan** [comment] 2020-10-22 12:53
Fixed via #518

**Closed by hyyan** 2020-10-22 12:53 UTC

**Comment by janis-ps** [comment] 2021-01-11 12:10
#518 was reverted, because it caused a breakage via an unrelated change.

So people are still looking for solutions to this.

**Comment by GeertSurkijn** [comment] 2021-01-14 13:36
Also suffering from this...

**Comment by fansorge** [comment] 2021-02-03 22:18
also suffering from this - and i tried using the fix mentioned by @janis-ps above. Nice indeed until i found that on each change in a product with variations the language variations are newly createed instead of synced with the newest changes...
