### ISSUE TITLE
Page translations

### ISSUE THREAD

**Issue by aakkii** [hyyan/woo-poly-integration#2] opened 2015-04-29 19:26 UTC
Hi!

First of all, thank you for your work, the plugin is great. 
But I have a little problem here. I installed Polylang, WooCommerce, and your plugin. (I'm using two languages on my site.) Then I tried to add a new page translation to the 'Shop' page generated by WooCommerce, and I got the followin error message:
`Fatal error: Using $this when not in object context in /<page-root>/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Meta.php on line 47`
Could you please give me a hint what I'm doing wrong, or how am I supposed to configure the shop, cart, product page, etc. translations? 

Thank you in advance, I really appreciate your help.

**Comment by hyyan** [comment] 2015-04-29 21:13
Hey @aakkii .

Thanks for opening this issue , actually you are not doing any thing wrong , the problem is that using `$this` in anonymous function was added in PHP5.4 and it seems you have another version of PHP .

The plugin must be function correctly in PHP5.3 , and I will fix this immediately . 
Thanks :)

**Comment by hyyan** [comment] 2015-04-29 21:33
@aakkii  Issue was fixed now in version 0.17.2

**Closed by hyyan** 2015-04-29 21:33 UTC
