### ISSUE TITLE
Products Attributes and Variations are not Translated to Others Languages

### ISSUE THREAD

**Issue by raz0r7** [hyyan/woo-poly-integration#452] opened 2019-08-09 03:09 UTC
## Can you reproduce this issue on default Wordpress theme (eg Storefront)?
No

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?

PHP: : 7.2.20
WordPress: 5.2.2
WooCommerce: Version 3.6.5
Polylang: Version 2.6.3
Hyyan WooCommerce Polylang Integration: 1.4.3
Browser: Chrome 76.0.3809.100

#### Steps to Reproduce

1. Import a product from AliExpress in English via AliDropShip plugin
2. Edit that product in default language(English). Save and Publish.
3. Click on + to add translated versions of the same product.
4. Publish the products in Spanish and Portuguese

#### What I Expected

Have all attributes and products variations translated to the products language versions, e.g. Spanish and Portuguese

#### What Happened Instead

Those Attributes and variations are not translated and remains in the default language, which is in English. 
All fields in "strings translations" settings are already translated in English, Spanish and Portuguese

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://shopflixstore.com
Site address (URL): https://shopflixstore.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.20
PHP Post Max Size: 256 MB
PHP Time Limit: 240
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 34.07MB
Database Data Size: 22.32MB
Database Index Size: 11.75MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adsw_activities: Data: 0.27MB + Index: 0.00MB
wp_adsw_ali_meta: Data: 0.31MB + Index: 0.03MB
wp_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB
wp_ads_activities: Data: 0.02MB + Index: 0.00MB
wp_ads_ali_meta: Data: 0.02MB + Index: 0.03MB
wp_ads_attributes: Data: 0.02MB + Index: 0.03MB
wp_ads_orders_item: Data: 0.02MB + Index: 0.03MB
wp_ads_products: Data: 0.02MB + Index: 0.03MB
wp_ads_products_meta: Data: 0.02MB + Index: 0.02MB
wp_ads_search_analytics: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.30MB + Index: 0.38MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.16MB + Index: 0.14MB
wp_payment_discount: Data: 0.02MB + Index: 0.00MB
wp_payment_transaction: Data: 0.02MB + Index: 0.06MB
wp_postmeta: Data: 12.52MB + Index: 7.56MB
wp_posts: Data: 3.52MB + Index: 0.81MB
wp_termmeta: Data: 0.19MB + Index: 0.27MB
wp_terms: Data: 0.22MB + Index: 0.22MB
wp_term_relationships: Data: 1.34MB + Index: 0.41MB
wp_term_taxonomy: Data: 0.31MB + Index: 0.31MB
wp_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.47MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 1011
custom_css: 1
customize_changeset: 5
elementor_library: 7
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 100
page: 60
polylang_mo: 3
post: 3
product: 186
product_variation: 1964
revision: 16
scheduled-action: 697
wpcf7_contact_form: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Polylang: by WP SYNTEX – 2.6.3
Livemesh Addons for Elementor: by Livemesh – 2.7.4
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin & Denis Zharov – 1.5.8
All In One SEO Pack: by Michael Torbert – 3.2.3
All-in-One WP Migration File Extension: by ServMask
Inc. – 1.5

All-in-One WP Migration: by ServMask – 7.4
WooCommerce MercadoPago: by Mercado Pago – 3.1.0 – Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Polylang Connect for Elementor: by David Decker - DECKERWEB – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Display PHP Version: by David Gwyer – 1.5
Elementor: by Elementor.com – 2.6.8
Envato Elements: by Envato – 1.1.1
Essential Addons for Elementor: by WPDeveloper – 3.1.5
Site Kit by Google: by Google – 1.0.0-beta.1.0.3
My Custom Functions: by Space X-Chimp – 4.38.1
Ocean Custom Sidebar: by OceanWP – 1.0.4
Ocean Extra: by OceanWP – 1.5.10
Ocean Product Sharing: by OceanWP – 1.0.7 – Not tested with the active version of WooCommerce
Ocean Social Sharing: by OceanWP – 1.0.14
Ocean Stick Anything: by OceanWP – 1.0.2
One Click Demo Import: by ProteusThemes – 2.5.2
PowerPack Lite for Elementor: by IdeaBox Creations – 1.2.5
Premium Addons for Elementor: by Leap13 – 3.6.4
Shortcode in Menus: by Gagan Deep Singh – 3.5
Sticky Header OceanWP: by Oren Hahiashvili – 1.0.5
TI WooCommerce Wishlist Plugin: by TemplateInvaders – 1.13.2
Toolbar Extras: by David Decker - DECKERWEB – 1.4.4
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.4.3
WooCommerce Refund and Exchange Lite: by MakeWebBetter – 1.0.5
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WooCommerce Services: by Automattic – 1.21.0
WooCommerce: by Automattic – 3.6.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.11

WPForms Lite: by WPForms – 1.5.4.2

### Inactive Plugins (4) ###

Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

Duplicator: by Snap Creek – 1.3.18
Jetpack by WordPress.com: by Automattic – 7.6
WooCommerce Quick Buy: by Varun Sridharan – 1.9 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #1573 - /terms-of-service/

### Theme ###

Name: OceanWP
Version: 1.6.10
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 696
Oldest: 2019-07-09 00:51:26 -0300
Newest: 2019-08-08 23:21:55 -0300

Pending: 1
Oldest: 2019-08-09 00:21:55 -0300
Newest: 2019-08-09 00:21:55 -0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by Jon007** [comment] 2019-08-10 10:08
are the product attributes set up under Products, Attributes?  see https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

Attributes which are set up individually on each product and not created in Products, Attributes cannot be translated automatically and are not added to Strings Translation.
Variation descriptions would need to be translated individually on the translated variations.

**Comment by raz0r7** [comment] 2019-08-12 00:10
Hi Jon,

Actually its all imported via AliDropShip Plugin, but I found in this article very nice information. Will check and translate de terms. Thank you very much!

This is not the only issue which is happening. The attributes are lost when adding new product translation to Spanish or Portuguese. It does not happen in all products, but mains with the ones which have more than 4, 5 variations, fos example:

Colors: WHITE / BLACK / BEIGE
Product size: S M L XL XXL

Such case, almost always the attributes are lost and I have to link them manually.

This is a products example:
https://shopflixstore.com/product/posture-corrector-magnetic-therapy/

In the moment draft are saving,  it looses the variations right away and in dropbox are set "any color / "any size", then I need to go to AliExpress site and cross check the quantity in stock to match the correct options and set it manually. This is bothering me a lot.

**Comment by Jon007** [comment] 2019-08-14 06:36
it seems to be down..

**Comment by raz0r7** [comment] 2019-08-14 10:59
I made some changes and most likely this product was removed.
I had to set it all manually.

Just created it now: https://shopflixstore.com/product/4-colors-oxford-harness-dog-leash-collar/

This time, Portuguese has more options than English, will leave at it is just for you to see.

![image](https://user-images.githubusercontent.com/53522096/63016185-5b0e0600-be69-11e9-94ac-ca6edc603494.png)

**Comment by Jon007** [comment] 2019-08-15 23:28
Hi @raz0r7  I retested with 9 variations based on 2 attributes, and using 3 languages and I dont see a problem.
Could this be related to the other AliDropShip problems?
Can you reproduce any problem when AliDropShip etc are not used?

**Comment by raz0r7** [comment] 2019-08-16 04:32
Hi Jon,

AliDropShip plugin is responsible for importing and managing the products on the site. Deactivating it cashes the product list, database errors happens and is impossible to move forward. I wish I could check the site with this plugin deactivated for testing purposes.

Its totally related to AliDropShip problems for sure.

They have a forum and a KB site:

Forum
https://forum.alidropship.com/

KB
https://help.alidropship.com/en/

**Comment by Jon007** [comment] 2020-06-28 17:57
Closing as This plugin only provides compatibility with WooCommerce itself, other WooCommerce extensions may need additional translation compatibility layer. This is only a free plugin maintained by volunteers and cannot provide compatibility extensions for all plugins.  Also noted that there are also several different drop ship plugins which would need their own compatibility layers with WooCommerce and also would need retesting for recent updates to all plugins.

**Closed by Jon007** 2020-06-28 17:57 UTC
