### ISSUE TITLE
Cart custom price via set_price broken by translation

### ISSUE THREAD

**Issue by samsk** [hyyan/woo-poly-integration#233] opened 2017-09-19 21:25 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: 4.8.1
* WooCommerce:  3.1.2
* Polylang: 1.0.3
* Hyyan WooCommerce Polylang Integration: 2.2.1
* Browser: Firefox 55.0.3

#### Steps to Reproduce
1. Have product with price 1
2. Try to dynamically override this product price i.e. using this legal code

add_action( 'woocommerce_before_calculate_totals', 'add_custom_price' );

function add_custom_price( $cart_object ) {
    $custom_price = 10; // This will be your custom price  
    foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
        $cart_item['data']->set_price($custom_price);   
    }
}

#### What I Expected

After adding product to Cart it should have price 10, and total price should be 10.

#### What Happened Instead

Product in Cart has price 1, but total price is 10.

#### Possible cause

From a quick debugging, translateCartItemProduct hook uses smth. like set_price(get_regular_price()), and therefore sets back regular product price, while dismissing the custom one.

**Comment by Jon007** [comment] 2017-09-20 10:22
This looks like expected behaviour.

This plugin doesn't do any price calculations but it may change the actual product:  specifically, the user interface doesn't display the product added to the cart, it displays the translation of the product added to the cart in the current language, which would cause the behaviour you are seeing. 

So in this context woocommerce_before_calculate_totals would not be a suitable place to change the individual product price.

If you actually want to change the displayed product price then the correct solution may depend on the full use case.   For example to implement currency conversion, you would filter on:
                add_filter('woocommerce_product_get_price', ....
                add_filter('woocommerce_product_variation_get_price', ...
                add_filter('woocommerce_product_variation_get_regular_price',  ...
                add_filter('woocommerce_product_variation_get_sale_price'  ...

**Comment by hyyan** [comment] 2017-12-05 07:14
Closing as @Jon007  made this clear and it is not part of the plugin implementation.
@samsk Please feel free to re-open in case you have any issue

**Closed by hyyan** 2017-12-05 07:14 UTC
