### ISSUE TITLE
Stock sync fail

### ISSUE THREAD

**Issue by carlituxman** [hyyan/woo-poly-integration#334] opened 2018-04-27 15:31 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6
* WordPress: 4.9.5
* WooCommerce: 3.3.5
* Polylang: 2.3.4
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Chrome 66.0.3359.117

#### Steps to Reproduce
We have 3 langs: Spanish, English and Portuguese and sync stock activated (with all checks on meta too). The item has 1 in stock, the default lang is ES and in the other langs we can't edit the quantity.
The item is sold in ES version, then the stock in EN and PT is 1 and in ES is 0. The Stock has not been synced.

#### What I Expected
The sync of the stock.

#### What Happened Instead
The stock hasn't synced. If we open the product at backend and press Update button, then the stock is sync.

## WordPress Environment
no errors

**Comment by Jon007** [comment] 2018-04-27 19:05
this appears to be a duplicate of an issue with a proposed fix, please try the fix and comment on that issue,
see #299 with fix #300

**Closed by Jon007** 2018-04-27 19:05 UTC

**Comment by carlituxman** [comment] 2018-05-02 11:37
solved with 1.1.0 version. thanks!
