### ISSUE TITLE
Breadcrumb SHOP main category missing in second language

### ISSUE THREAD

**Issue by fazio79** [hyyan/woo-poly-integration#541] opened 2021-02-23 18:03 UTC
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
No if I disable Hyyan WooCommerce Polylang the problem disappear

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.23
* WordPress: 5.6.2
* WooCommerce: 4.9.2
* Polylang: 2.9.1 
* Hyyan WooCommerce Polylang Integration: 1.5.0
* Browser: Chrome  88.0.4324.182 

#### Steps to Reproduce
1. Go to https://www.edarcom.it/shop/
2. Select one item in the shop
3. The breadcrumb shows HOME / SHOP / [ITEM CATEGORY] / [ITEM TITLE]
4. Switch language from ITALIAN to ENGLISH (flags on top left)
5. The breadcrumb shows HOME / [ITEM CATEGORY] / [ITEM TITLE] 

#### What I Expected
The breadcrumb should shows HOME / SHOP / [ITEM CATEGORY] / [ITEM TITLE] for both languages

#### What Happened Instead
Generally switching from the default language to english the path SHOP disappear from the breadcrumb inside woocommerce

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.edarcom.it
Site address (URL): https://www.edarcom.it
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.23
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 100000
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB-log-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: ciqti_
Dimensione totale database: 51.73MB
Dimensione dati database: 44.20MB
Dimensione indice database: 7.53MB
ciqti_woocommerce_sessions: Dati: 10.76MB + indice: 0.56MB + motore MyISAM
ciqti_woocommerce_api_keys: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_order_items: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_order_itemmeta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
ciqti_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_shipping_zone_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_actionscheduler_actions: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
ciqti_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_action: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_automation: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_campaign: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_condition: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_configuration: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_field: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_list: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_mail: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_mail_has_list: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_mail_stat: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_queue: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_rule: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_step: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_tag: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_url: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_acym_url_click: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_user: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_acym_user_has_field: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_user_has_list: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_acym_user_stat: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_aiowps_events: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_aiowps_failed_logins: Dati: 0.14MB + indice: 0.04MB + motore MyISAM
ciqti_aiowps_global_meta: Dati: 9.63MB + indice: 0.00MB + motore MyISAM
ciqti_aiowps_login_activity: Dati: 0.03MB + indice: 0.01MB + motore MyISAM
ciqti_aiowps_login_lockdown: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_aiowps_permanent_block: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_commentmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_comments: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
ciqti_elfsight_instalink_widgets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_cache: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_comments: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_image_cache: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_options: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_posts: Dati: 0.19MB + indice: 0.01MB + motore MyISAM
ciqti_ffi_post_media: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_snapshots: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_streams: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ffi_streams_sources: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_mgmlp_folders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_newsletter: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
ciqti_newsletter_emails: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_newsletter_sent: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_newsletter_stats: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_newsletter_user_logs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_options: Dati: 3.07MB + indice: 0.16MB + motore MyISAM
ciqti_postmeta: Dati: 6.87MB + indice: 2.73MB + motore MyISAM
ciqti_posts: Dati: 6.89MB + indice: 0.48MB + motore MyISAM
ciqti_redirection_404: Dati: 1.79MB + indice: 0.29MB + motore MyISAM
ciqti_redirection_groups: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_redirection_items: Dati: 0.01MB + indice: 0.02MB + motore MyISAM
ciqti_redirection_logs: Dati: 0.11MB + indice: 0.03MB + motore MyISAM
ciqti_revslider_css: Dati: 0.09MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_css_bkp: Dati: 0.09MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_layer_animations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_layer_animations_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_navigations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_navigations_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_sliders: Dati: 0.06MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_sliders_bkp: Dati: 0.05MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_slides: Dati: 0.27MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_slides_bkp: Dati: 0.22MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_static_slides: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_revslider_static_slides_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_termmeta: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
ciqti_terms: Dati: 0.06MB + indice: 0.11MB + motore MyISAM
ciqti_term_relationships: Dati: 0.26MB + indice: 0.54MB + motore MyISAM
ciqti_term_taxonomy: Dati: 0.09MB + indice: 0.10MB + motore MyISAM
ciqti_ulp_campaigns: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_campaign_items: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_layers: Dati: 0.28MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_popups: Dati: 0.08MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_subscribers: Dati: 0.13MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_targets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_ulp_webfonts: Dati: 0.05MB + indice: 0.01MB + motore MyISAM
ciqti_usermeta: Dati: 1.46MB + indice: 0.95MB + motore MyISAM
ciqti_users: Dati: 0.17MB + indice: 0.16MB + motore MyISAM
ciqti_wcpdf_invoice_number: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
ciqti_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
ciqti_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
ciqti_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
ciqti_wc_product_meta_lookup: Dati: 0.07MB + indice: 0.12MB + motore MyISAM
ciqti_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
ciqti_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
ciqti_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
ciqti_yith_wcwl: Dati: 0.22MB + indice: 0.12MB + motore MyISAM
ciqti_yith_wcwl_lists: Dati: 0.34MB + indice: 0.33MB + motore MyISAM

### Post Type Counts ###

attachment: 705
cf7sg_page: 3
custom_css: 1
customize_changeset: 2
dzswtl_list_layout: 2
mfds_form_entry: 223
mgmlp_media_folder: 150
nav_menu_item: 175
page: 100
polylang_mo: 2
post: 99
product: 881
pwfw: 1
revision: 1630
rl_gallery: 4
shop_coupon: 5
shop_order: 2
templatica_template: 1
vc_grid_item: 9
wcp_carousel: 2
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Polylang: by WP SYNTEX – 2.9.2
Akismet Anti-Spam: by Automattic – 4.1.8
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.7

CF7 Smart Grid Design Extension: by Aurovrata V. – 4.8.1
Contact Form 7 Polylang extension: by Aurovrata V. – 2.4.0
Classic Editor: by Contributori WordPress – 1.6
CMB2: by CMB2 team – 2.8.0
Contact Form 7 Captcha Pro: by 247wd – 0.0.8
Contact Form 7 - Dynamic Text Extension: by Chris Mavricos
SevenSpark – 2.0.3

Contact Form 7: by Takayuki Miyoshi – 5.3.2
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.0.3
Create And Assign Categories For Pages: by Sandeep Singh – 1.1
Dropdown Menu Widget: by Metin Saylan – 1.9.7
Duplicate Menu: by Jonathan Christopher – 0.2.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
Elfsight InstaLink: by Elfsight – 2.1.10
WPBakery Page Builder: by Michael M - WPBakery.com – 6.5.0
Layered Popups: by Halfdata
Inc. – 6.50

Multi Form Data Storage: by QuanticaLabs – 1.1
Newsletter: by Stefano Lissa
The Newsletter Team – 7.0.3

No CAPTCHA reCAPTCHA for WooCommerce: by MailOptin Team – 1.2.6
One Click Remove Menu: by Max – 1.0.0
Really Simple SSL: by Really Simple Plugins – 4.0.9
Redirection: by John Godley – 5.0.1
Redux: by Redux.io + Dovy Paukstys – 4.1.24
Responsive Lightbox & Gallery: by dFactory – 2.3.2
Responsive Posts Carousel Pro: by WebCodingPlace – 13.6
Slider Revolution: by ThemePunch – 6.3.6
Stop Spammers: by Trumani – 2021.1
UpdraftPlus - Backup/Ripristino: by UpdraftPlus.Com
DavidAnderson – 1.16.47

User Verification: by PickPlugins – 1.0.53
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.5.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 4.9.2 (aggiornamento alla versione 5.0.0 disponibile)
Artday Shortcodes: by WossThemes – 1.3
WP Media folder: by Joomunited – 4.5.4
YITH WooCommerce Wishlist: by YITH – 3.0.20

### Inactive Plugins (1) ###

WooCommerce shop builder - Create any shop grid / table with advanced filters: by Digital Zoom Studio – 1.18

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #9 - /shop/
Carrello: #10 - /carrello/
Pagamento: #11 - /checkout/
Il mio account: #12 - /my-account/
Termini e condizioni: #1305 - /condizioni-di-vendita/

### Theme ###

Name: edarcom Child Theme
Version: 1.1.1
Author URL: http://themeforest.net/user/wossthemes
Child Theme: ✔
Parent Theme Name: edarcom
Parent Theme Version: 1.8.3
Parent Theme Author URL: http://themeforest.net/user/wossthemes
WooCommerce Support: ✔

### Templates ###

Overrides: edarcom-child/woocommerce/archive-product.php
edarcom/woocommerce/cart/cart-totals.php
edarcom/woocommerce/cart/cart.php
edarcom/woocommerce/cart/proceed-to-checkout-button.php
edarcom/woocommerce/cart/shipping-calculator.php
edarcom-child/woocommerce/checkout/form-billing.php
edarcom/woocommerce/checkout/form-checkout.php
edarcom/woocommerce/checkout/form-coupon.php
edarcom-child/woocommerce/checkout/form-shipping.php
edarcom/woocommerce/content-product-cat.php
edarcom-child/woocommerce/content-product.php
edarcom-child/woocommerce/emails/customer-on-hold-order.php versione 3.5.0 è obsoleta. La versione attuale è 3.7.0
edarcom-child/woocommerce/global/form-login.php
edarcom-child/woocommerce/global/quantity-input.php versione 3.6.0 è obsoleta. La versione attuale è 4.0.0
edarcom/woocommerce/global/wrapper-end.php
edarcom/woocommerce/global/wrapper-start.php
edarcom/woocommerce/loop/loop-end.php
edarcom/woocommerce/loop/loop-start.php
edarcom-child/woocommerce/myaccount/dashboard.php versione 2.6.0 è obsoleta. La versione attuale è 4.4.0
edarcom-child/woocommerce/myaccount/form-login.php versione 3.6.0 è obsoleta. La versione attuale è 4.1.0
edarcom/woocommerce/myaccount/form-lost-password.php
edarcom/woocommerce/myaccount/my-address.php
edarcom/woocommerce/myaccount/view-order.php
edarcom/woocommerce/notices/error.php
edarcom/woocommerce/notices/notice.php
edarcom/woocommerce/notices/success.php
edarcom/woocommerce/order/order-details-customer.php
edarcom/woocommerce/order/order-details.php
edarcom/woocommerce/single-product/add-to-cart/simple.php
edarcom/woocommerce/single-product/product-image.php
edarcom/woocommerce/single-product/related.php
edarcom/woocommerce/single-product/tabs/additional-information.php
edarcom/woocommerce/single-product/tabs/description.php
edarcom/woocommerce/single-product/tabs/tabs.php
edarcom-child/woocommerce/single-product-reviews.php versione 3.6.0 è obsoleta. La versione attuale è 4.3.0
edarcom/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Scopri come aggiornare

### Action Scheduler ###

Completato: 11
Oldest: 2021-01-23 20:28:51 +0100
Newest: 2021-02-23 17:14:50 +0100

In attesa: 1
Oldest: 2021-02-27 20:35:19 +0100
Newest: 2021-02-27 20:35:19 +0100

### WooCommerce Polylang Integration ###

Language Locale: it_IT
Polylang Language Locale: it_IT
Polylang Available Languages: it_IT (WooCommerce translation file found OK at /home/edarcomi/public_html/wp-content/languages/plugins/woocommerce-it_IT.mo) en_GB (WooCommerce translation file found OK at /home/edarcomi/public_html/wp-content/languages/plugins/woocommerce-en_GB.mo)
`
</details>

**Comment by Jon007** [comment] 2021-02-25 11:01
closing as  duplicate of #542

**Closed by Jon007** 2021-02-25 11:01 UTC
