### ISSUE TITLE
Product image disappear on a new product

### ISSUE THREAD

**Issue by jardinfantome** [hyyan/woo-poly-integration#305] opened 2018-02-20 17:37 UTC
#### What product versions and settings are you using when this issue occurs?
* PHP: 	7.0.27
* WordPress: 	4.9.4
* WooCommerce: 3.3.1
* Polylang: [state if using Polylang PRO] Version 2.3.1
* Hyyan WooCommerce Polylang Integration: Version 1.0.4
* Browser: Chrome/Safari

#### Steps to Reproduce
Add a new product
Add a product image
Save

#### What I Expected
The image is uploaded and I can save the new product. The new product is created and the picture is on the page of the product and on the homepage with every other product.

#### What Happened Instead
I don't see the image uploaded, I can save the new product. The new product is created but I can see the picture only on the homepage and not on the page of the product. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment] 2018-02-21 02:12
This is most likely down to the theme.
But we can't tell because you did not answer the question:
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

This could also be a duplicate of #293 but I can't tell because you have not attached the WooCommerce, System Status information as requested 

This plugin is supported by volunteers in their spare time, please respect the time of other people by providing the relevant information when raising an issue.

**Closed by Jon007** 2018-02-21 02:12 UTC

**Comment by jardinfantome** [comment] 2018-02-21 14:10
Sorry I'm a beginner so I don't understand everything. I've made this comment because I can reproduce this issue on default Wordpress theme like Storefront and I can reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration. 

Here all the woocommerce system status : 

``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here. 
`
### WordPress Environment ###

Home URL: https://jardinfantome.com
Site URL: https://jardinfantome.com
WC Version: 3.3.2
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 130 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.2
WC Database Prefix: mod657_
Taille totale de la base de données: 46.64MB
Taille de la base de données: 32.64MB
Taille de l’index: 14.00MB
mod657_woocommerce_sessions: Donnée : 0.02MB + Index: 0.02MB
mod657_woocommerce_api_keys: Donnée : 0.02MB + Index: 0.03MB
mod657_woocommerce_attribute_taxonomies: Donnée : 0.02MB + Index: 0.02MB
mod657_woocommerce_downloadable_product_permissions: Donnée : 0.02MB + Index: 0.05MB
mod657_woocommerce_order_items: Donnée : 0.02MB + Index: 0.02MB
mod657_woocommerce_order_itemmeta: Donnée : 0.02MB + Index: 0.03MB
mod657_woocommerce_tax_rates: Donnée : 0.02MB + Index: 0.06MB
mod657_woocommerce_tax_rate_locations: Donnée : 0.02MB + Index: 0.05MB
mod657_woocommerce_shipping_zones: Donnée : 0.02MB + Index: 0.00MB
mod657_woocommerce_shipping_zone_locations: Donnée : 0.02MB + Index: 0.05MB
mod657_woocommerce_shipping_zone_methods: Donnée : 0.02MB + Index: 0.00MB
mod657_woocommerce_payment_tokens: Donnée : 0.02MB + Index: 0.02MB
mod657_woocommerce_payment_tokenmeta: Donnée : 0.02MB + Index: 0.03MB
mod657_woocommerce_log: Donnée : 0.02MB + Index: 0.02MB
mod657_cdi: Donnée : 0.02MB + Index: 0.02MB
mod657_cfs_contacts: Donnée : 0.02MB + Index: 0.00MB
mod657_cfs_countries: Donnée : 0.02MB + Index: 0.00MB
mod657_cfs_forms: Donnée : 0.22MB + Index: 0.00MB
mod657_cfs_membership_presets: Donnée : 0.02MB + Index: 0.00MB
mod657_cfs_statistics: Donnée : 0.02MB + Index: 0.00MB
mod657_commentmeta: Donnée : 0.02MB + Index: 0.03MB
mod657_comments: Donnée : 0.02MB + Index: 0.09MB
mod657_gde_profiles: Donnée : 0.00MB + Index: 0.00MB
mod657_gde_secure: Donnée : 0.00MB + Index: 0.00MB
mod657_links: Donnée : 0.02MB + Index: 0.02MB
mod657_nbs_forms: Donnée : 0.06MB + Index: 0.00MB
mod657_nbs_newsletters: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_newsletters_to_lists: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_octo: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_octo_blocks: Donnée : 1.52MB + Index: 0.00MB
mod657_nbs_octo_blocks_mission: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_subscribers: Donnée : 0.14MB + Index: 0.00MB
mod657_nbs_subscribers_lists: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_subscribers_to_lists: Donnée : 0.02MB + Index: 0.00MB
mod657_nbs_subscribers_to_lists_prev: Donnée : 0.02MB + Index: 0.00MB
mod657_newsletter: Donnée : 0.00MB + Index: 0.00MB
mod657_newsletter_emails: Donnée : 0.02MB + Index: 0.00MB
mod657_newsletter_sent: Donnée : 0.00MB + Index: 0.00MB
mod657_newsletter_stats: Donnée : 0.02MB + Index: 0.00MB
mod657_options: Donnée : 22.11MB + Index: 10.25MB
mod657_postmeta: Donnée : 3.39MB + Index: 2.56MB
mod657_posts: Donnée : 1.13MB + Index: 0.23MB
mod657_pps_countries: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_modules: Donnée : 0.02MB + Index: 0.02MB
mod657_pps_modules_type: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_popup: Donnée : 2.31MB + Index: 0.00MB
mod657_pps_popup_show_categories: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_popup_show_pages: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_statistics: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_subscribers: Donnée : 0.02MB + Index: 0.00MB
mod657_pps_usage_stat: Donnée : 0.02MB + Index: 0.02MB
mod657_termmeta: Donnée : 0.02MB + Index: 0.03MB
mod657_terms: Donnée : 0.02MB + Index: 0.03MB
mod657_term_relationships: Donnée : 0.09MB + Index: 0.06MB
mod657_term_taxonomy: Donnée : 0.05MB + Index: 0.03MB
mod657_UPCP_Catalogues: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Catalogue_Items: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Categories: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Custom_Fields: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Fields_Meta: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Items: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Item_Images: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_SubCategories: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Tagged_Items: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Tags: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Tag_Groups: Donnée : 0.02MB + Index: 0.00MB
mod657_UPCP_Videos: Donnée : 0.02MB + Index: 0.00MB
mod657_usermeta: Donnée : 0.05MB + Index: 0.03MB
mod657_users: Donnée : 0.02MB + Index: 0.05MB
mod657_wc_download_log: Donnée : 0.02MB + Index: 0.03MB
mod657_wc_webhooks: Donnée : 0.02MB + Index: 0.02MB
mod657_wysija_campaign: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_campaign_list: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_custom_field: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_email: Donnée : 0.11MB + Index: 0.00MB
mod657_wysija_email_user_stat: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_email_user_url: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_form: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_list: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_queue: Donnée : 0.02MB + Index: 0.02MB
mod657_wysija_subscriber_ips: Donnée : 0.02MB + Index: 0.02MB
mod657_wysija_url: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_url_mail: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_user: Donnée : 0.02MB + Index: 0.02MB
mod657_wysija_user_field: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_user_history: Donnée : 0.02MB + Index: 0.00MB
mod657_wysija_user_list: Donnée : 0.02MB + Index: 0.00MB
mod657_yoast_seo_links: Donnée : 0.02MB + Index: 0.02MB
mod657_yoast_seo_meta: Donnée : 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 323
custom_css: 1
customize_changeset: 4
cycloneslider: 1
nav_menu_item: 41
page: 27
polylang_mo: 2
popup: 1
popup_theme: 6
post: 2
product: 72
product_variation: 609
psfb: 3
revision: 147
shop_coupon: 1
shop_order: 4
tablepress_table: 4
wpcf7_contact_form: 3
wpforms: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Polylang: par Frédéric Demarle – 2.3.1
AfterShip - WooCommerce Tracking: par AfterShip – 1.7.9 – Non testé avec la version active de WooCommerce
Akismet Anti-Spam: par Automattic – 4.0.3
Autoptimize: par Frank Goossens (futtta) – 2.3.2
Child Theme Configurator: par Lilaea Media – 2.2.8.1
Colissimo Delivery Integration: par Harasse – 2.0.7 – Non testé avec la version active de WooCommerce
Contact Form 7: par Takayuki Miyoshi – 5.0
Diaporama: par Nico Amarilla – 3.2.0
Google Analytics Dashboard for WP (GADWP): par Alin Marcu – 5.2.2
Google Doc Embedder: par Kevin Davis
Dan Lester – 2.6.4

PlanSo Forms: par PlanSo.de – 2.6.0
Popup by Supsystic: par supsystic.com – 1.9.20
Really Simple SSL: par Rogier Lankhorst – 2.5.25
SI Captcha Anti-Spam: par fastsecure – 3.0.3 – Non testé avec la version active de WooCommerce
TablePress: par Tobias Bäthge – 1.9
W3 Total Cache: par Frederick Townes – 0.9.6
Hyyan WooCommerce Polylang Integration: par Hyyan Abo Fakher – 1.0.4 – Non testé avec la version active de WooCommerce
WooCommerce PayPal Express Checkout Gateway: par WooCommerce – 1.5.2
WooCommerce Stripe Gateway: par WooCommerce – 4.0.6
WooCommerce: par Automattic – 3.3.2
Yoast SEO: par L’équipe Yoast – 6.3.1
MailPoet 2: par MailPoet – 2.8.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base boutique: #4 - /boutique/
Panier: #5 - /mon-panier/
Commande: #6 - /ma-commande/
Mon compte: #7 - /mon-compte/
Conditions générales de vente et d’utilisation: #100 - /cgv/

### Theme ###

Name: Shop Isle Child
Version: 2.2.9.1491322989
Author URL: //themeisle.com
Child Theme: ✔
Parent Theme Name: Shop Isle
Parent Theme Version: 2.2.10
Parent Theme Author URL: https://themeisle.com
WooCommerce Support: ✔

### Templates ###

Overrides: shop-isle-child/woocommerce/emails/customer-completed-order.php
````

**Comment by Jon007** [comment] 2018-02-21 14:28
I received a further email about this stating:
"
Sorry I'm a beginner so I don't understand everything. I've made this comment because I can reproduce this issue on default Wordpress theme like Storefront and I can reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration.
"

However the system status report also included showed 22 plugins activated including:
WooCommerce PayPal Express Checkout Gateway: par WooCommerce – 1.5.2
which is known to cause this issue as per #293 - please see this issue and test the solution there (or simply disable WooCommerce PayPal Express Checkout Gateway and use the built-in woocommerce Paypal gateway instead.

**Comment by jardinfantome** [comment] 2018-02-21 17:30
thank you really much ! It works !
