### ISSUE TITLE
Redirect after payment gateway ignores language

### ISSUE THREAD

**Issue by repli2dev** [hyyan/woo-poly-integration#118] opened 2017-01-27 12:59 UTC
I am testing a bit your plugin prior rollout to our production system and I have probably encountered a bug.

The cart, checkout are translated all the way to payment... Then I am redirected to the gateway, payment suceeded and when I am returned back the by the `WC_Abstract_Order::get_checkout_order_received_url` to the `order-received` in the default language, not language of order.

I have debuged the code via xdebug and I see that first time the URL is correct (before going to payment gateway), however after the payment it is not.

Is this a bug? Have anyone else encounered it? Could that be fixed?
Thanks!

**Comment by Longhot** [comment] 2017-02-01 10:23
Hello, same problème.
I Add this in functions.php from my theme: (commande is my page defined in woocommerce setings page)

function DSI_NewCommandePermalink( $permalink ) {
	return  str_replace("/commande/", "/".pll_current_language()."/commande/", $permalink);
}
add_filter('woocommerce_get_checkout_page_permalink', DSI_NewCommandePermalink, 10, 1);

I know this is not super stylish as a method, but it works.
To do this, you would have to change the woocommerce settings according to the language to return the correct page, but I do not have time to start this long task.

Have you found a better solution?

**Comment by Longhot** [comment] 2017-02-01 10:29
Same solution for the "shop" page

**Comment by Longhot** [comment] 2017-02-06 14:47
https://polylang.pro/doc/translating-woocommerce-urls-and-strings/

**Comment by repli2dev** [comment] 2017-02-06 21:28
@Longhot what is purpose of the link? (As this is for different plugin.)

**Comment by Longhot** [comment] 2017-02-07 07:24
@ repli2dev
Sorry I do not speak good English.
I had this problem too.

First I had made a filter in functions.php (not good; ().

Then by consulting the link which I indicated, I found when configuring correctly woocommerce everything worked perfectly.

My stages: I duplicated my pages ( endpoints ) in the deliberate languages.
In the configuration of woocoomerce put endpoints according to every languages.

You found a solution?

![image](https://cloud.githubusercontent.com/assets/25476476/22681275/9aeb9cbe-ed0c-11e6-88d8-a09caa3ef2c2.png)
![image](https://cloud.githubusercontent.com/assets/25476476/22681286/a78ca4ea-ed0c-11e6-96cf-705bb9c02154.png)

**Comment by repli2dev** [comment] 2017-03-06 09:19
@Longhot thanks for your response...

I mangled a bit with our wordpress and now it works properly, can't really tell what caused it... Despite that I think your input was valuable and got me on the right track. Thank you :-)

**Comment by repli2dev** [comment] 2017-03-06 10:03
Sadly, I have found that the situation was cause with non-presence of the woo-poly-integration plugin.. Also it says that the bug is caused by the plugin, so reopening.

**Comment by Jon007** [comment] 2017-04-25 17:01
Hi, I am not able to understand your situation:

What do you mean by "it says that the bug is caused by the plugin"  
- who or what says that?
- which payment gateway?

Note if you set a configuration in the 3rd party gateway to fix it to return to a fixed url that could cause the behaviour you see.

**Comment by repli2dev** [comment] 2017-05-04 14:13
@Jon007 Sorry for not precisely denoting my deduction, I will try one more.

I made two experiments
- the first one with this plugin enabled, result was that after paying at payment gateway I was returned to page of different language (I started in english, payed at gateway, ended up in czech).
- the second one with this plugin disabled, result was that after payment returned to the checkout page in same language as during the process of checkout before paying.

From that I would conclude (deduct) that this plugin is causing some problem with redirection.

Note: I am using GoPay gateway (https://www.gopay.com/en/) with Toret Gopay plugin (http://toret.cz/woocommerce-pluginy/woocommerce-gopay/) and there is no settings at all.

**Comment by Jon007** [comment] 2017-05-05 04:01
the results should be the other way around...:

 - which versions are you using of WooCommerce and woo-poly-integration ?
 - which is your primary language?
 - do you definitely have your woocommerce pages translated as Longhot says?  
 - are there any settings within GoPay itself?  (either on GoPay.com itself or within the plugin that might affect the return url?   [I never heard of GoPay before, I don't know about that, personally I use Paypal and Stripe]  
 - did you test both cases in both languages, ie starting with English, and starting in Czech?

**Comment by hyyan** [comment] 2017-06-05 15:56
Just Tried that with GoPay , it seems to work for me and I got redirected to the correct language.
Closing this one after testing, if this still an issue please provide more information about your setup  and repopen

**Closed by hyyan** 2017-06-05 15:56 UTC

**Comment by repli2dev** [comment] 2017-06-19 12:40
I used 0.29.1 and WooCommerce 2.6.14 and some local customizations (due to not sending e-mails etc). Primary language Czech (cz) and the pages are definitely translated and I am not aware of any GoPay settings.

Though this still happens not matter in language I start I always end up in Czech. With given versions the occurs in production too. With new version I will be able to retest in some time as the new version request WooCommerce 3.

**Comment by robizzt** [comment] 2019-04-04 09:24
Hello,
This happens for me, too.
I have translated all pages and all endpoints, and they all work when navigating through site.
But after payment gateway redirect to "order-received" page, no matter on what language I did the shopping, page is always in default language. But when I change in URL, for example "/checkout/order-received/" into Croatian language "/placanje/narudzba-zaprimljena/", page is show on Croation language perfectly.
Maybe redirection problem?

**Comment by Jon007** [comment] 2019-04-04 20:23
note that this is an old closed non-issue on an old version of the plugin.
Are you using a custom payment gateway?

Force resave your permalinks by saving on Settings, Permalinks, and then try with built-in payment methods.  If you still have issue, open as a new issue.

**Comment by fkoomek** [comment] 2019-04-30 15:12
Hi robizzt. What is your permalink structure? Are you using slugs for both languages?
I had a problem that the language slug was always cut from URL when I was trying to pay via Gateway using API. You might land on the page in default language cause of the same cause.

Using this filter solved my problem:
`add_filter('woocommerce_api_request_url', 'wt_woocommerce_api_request_url', 10, 3);
function wt_woocommerce_api_request_url($api_request_url, $request, $ssl) {
$currentlang = get_bloginfo('language');
switch ($currentlang) {
case "cs-CZ":
$lang = "/cs"; //adjust this to  fit your needs, please
break;
case "en-GB":
$lang = '/en'; //adjust this to  fit your needs, please
break;
default: $lang = '/en'; //adjust this to  fit your needs, please
}
if (is_null($ssl)) {
$scheme = wp_parse_url(home_url(), PHP_URL_SCHEME);
} elseif ($ssl) {
$scheme = 'https';
} else {
$scheme = 'http';
}
if (strstr(get_option('permalink_structure'), '/index.php/')) {
$api_request_url = trailingslashit(home_url($lang . '/index.php/wc-api/' . $request, $scheme));
} elseif (get_option('permalink_structure')) {
$api_request_url = trailingslashit(home_url($lang . '/wc-api/' . $request, $scheme));
} else {
$api_request_url = add_query_arg('wc-api', $request, trailingslashit(home_url('', $scheme)));
}
return $api_request_url;
}`
