### ISSUE TITLE
Conflict with "WooCommerce PayPal Express Checkout Gateway"

### ISSUE THREAD

**Issue by mgrom** [hyyan/woo-poly-integration#318] opened 2018-03-23 12:50 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes.
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
No.
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.34
* WordPress: 4.9.4
* WooCommerce: 3.3.4
* Polylang: 2.3.3
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Chrome, Edge

#### Steps to Reproduce
1. Install and activate WooCommerce PayPal Express Checkout Gateway
2. add featured image to post/page/product
3. chosen image isn't assigned to product

#### What I Expected

Image should show up in Featured image box, and should be saved to the post

#### What Happened Instead

Nothing

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://willow.prime-it.eu
Site URL: http://willow.prime-it.eu
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.34
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.0
GnuTLS/3.4.10

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: willow_
MaxMind GeoIP Database: ❌ Baza danych MaxMind GeoIP nie istnieje - Geolokalizacja nie będzie działać. Możesz pobrać i zainstalować ją ręcznie http://dev.maxmind.com/geoip/legacy/geolite/ stąd: . Przewiń w dół do zakładki "Downloads" i pobierz plik "Binary / gzip" obok "GeoLite Country". Pamiętaj
aby rozpakować GeoIP.dat.gz i przesłać tylko plik GeoIP.dat.

Całkowity rozmiar bazy danych: 22.98MB
Rozmiar bazy danych: 15.63MB
Rozmiar indeksu bazy danych: 7.35MB
willow_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB
willow_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
willow_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
willow_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
willow_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
willow_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB
willow_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
willow_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB
willow_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
willow_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB
willow_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
willow_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
willow_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
willow_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
willow_cn_social_icon: Dane: 0.02MB + Indeks: 0.00MB
willow_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
willow_comments: Dane: 0.02MB + Indeks: 0.08MB
willow_create_map: Dane: 0.00MB + Indeks: 0.00MB
willow_group_map: Dane: 0.00MB + Indeks: 0.00MB
willow_links: Dane: 0.02MB + Indeks: 0.02MB
willow_map_locations: Dane: 0.00MB + Indeks: 0.00MB
willow_options: Dane: 1.05MB + Indeks: 0.05MB
willow_postmeta: Dane: 8.52MB + Indeks: 4.03MB
willow_posts: Dane: 2.52MB + Indeks: 0.67MB
willow_termmeta: Dane: 0.09MB + Indeks: 0.11MB
willow_terms: Dane: 0.16MB + Indeks: 0.16MB
willow_term_relationships: Dane: 2.52MB + Indeks: 1.52MB
willow_term_taxonomy: Dane: 0.19MB + Indeks: 0.19MB
willow_usermeta: Dane: 0.16MB + Indeks: 0.03MB
willow_users: Dane: 0.02MB + Indeks: 0.05MB
willow_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
willow_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB

### Post Type Counts ###

attachment: 3196
custom_css: 1
customize_changeset: 20
nav_menu_item: 13
page: 19
polylang_mo: 3
post: 2
product: 738
revision: 32
shop_order: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ❌Komunikaty o błędach nie powinny być widoczne dla użytkowników.

### Active Plugins (14) ###

Polylang: przez Frédéric Demarle – 2.3.3
Bootstrap 3 Shortcodes: przez Michael W. Delaney
Filip Stefansson
and Simon Yeldon – 3.3.11

Bootstrap for Contact Form 7: przez Felix Arntz – 1.4.7
Contact Form 7: przez Takayuki Miyoshi – 5.0.1
Easy Social Icons: przez cybernetikz – 3.0.5
Loco Translate: przez Tim Whitlock – 2.1.2
myStickymenu: przez m.r.d.a – 2.0.4
Hyyan WooCommerce Polylang Integration: przez Hyyan Abo Fakher – 1.0.4 – Nietestowane z używaną wersją WooCommerce
WooCommerce PayPal Express Checkout Gateway: przez WooCommerce – 1.5.2
WooCommerce Product Stock Alert: przez WC Marketplace
The Grey Parrots – 1.4.8

WooCommerce Sequential Order Numbers: przez SkyVerge – 1.8.2 – Nietestowane z używaną wersją WooCommerce
WooCommerce: przez Automattic – 3.3.4
WooSwipe: przez Website Design – 1.1.6.6
WP Google Map Plugin: przez flippercode – 4.0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Strona sklepu: #4 - /pl/
Koszyk: #5 - /pl/koszyk/
Zamówienie: #6 - /pl/zamowienie/
Moje konto: #7 - /pl/moje-konto/
Regulamin: ❌ Strona nie ustawiona

### Theme ###

Name: WillowHandMade
Version: 1.0
Author URL: http://prime-it.eu
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: WillowHandMade/woocommerce/archive-product.php
WillowHandMade/woocommerce/auth/form-login.php
WillowHandMade/woocommerce/checkout/form-billing.php
WillowHandMade/woocommerce/checkout/form-coupon.php
WillowHandMade/woocommerce/content-product_cat.php
WillowHandMade/content-single-product.php
WillowHandMade/woocommerce/global/form-login.php
WillowHandMade/woocommerce/loop/loop-start.php
WillowHandMade/woocommerce/loop/result-count.php
WillowHandMade/woocommerce/myaccount/form-edit-account.php
WillowHandMade/woocommerce/myaccount/form-edit-address.php
WillowHandMade/woocommerce/myaccount/form-login.php
WillowHandMade/woocommerce/myaccount/form-lost-password.php
WillowHandMade/woocommerce/myaccount/my-account.php
WillowHandMade/woocommerce/product-searchform.php
WillowHandMade/woocommerce/single-product/add-to-cart/simple.php

`
```
</details>

**Comment by Jon007** [comment] 2018-03-28 09:59
Duplicate of #293 and others
There are plenty of ways of accepting PayPal which don’t introduce this problem including the Woocommerce default PayPal gateway and Angeleye

**Closed by Jon007** 2018-03-28 09:59 UTC
