### ISSUE TITLE
version 4.9.5

### ISSUE THREAD

**Issue by irenecruzdomene** [hyyan/woo-poly-integration#332] opened 2018-04-26 16:02 UTC
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.35
* WordPress: 4.9.5
* WooCommerce: 3.3.5
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: 

#### Steps to Reproduce
I place an order in Spanish, I go to the product, in Spanish the amount is reduced from 2 to 1 in the other languages ​​no, they are still 2 units.
I have to update the product to reduce units in all languages

#### What I Expected

I think it's due to the wordpress 4.9.5 update, I'd like to know when pluging compatible with this version will be updated

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment] 2018-04-27 06:42
The stock in languages problem is a duplicate of #299 which has a proposed fix of https://github.com/hyyan/woo-poly-integration/pull/300
[I haven't tested this as I don't use woocommerce stock management]

Also note this plugin does not yet support woocommerce 3.3.5, there is at least 1 important fix needed due to a change with breaks the language on all ajax calls.  This change  is proposed here:
https://github.com/hyyan/woo-poly-integration/pull/329

closing as duplicate of #299

**Closed by Jon007** 2018-04-27 06:42 UTC
