### ISSUE TITLE
Countries not translated at checkout form

### ISSUE THREAD

**Issue by williamvee5** [hyyan/woo-poly-integration#272] opened 2017-11-27 14:54 UTC
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.30
* WordPress: 4.9 
* WooCommerce: 3.2.5
* Polylang: not PRO 2.2.6
* Hyyan WooCommerce Polylang Integration:  1.0.3
* Browser: All
#### Steps to Reproduce
1. Add a product to cart, go to checkout, then select a country

#### What I Expected
Countries in dropdown to be translated in current locale.

#### What Happened Instead
Countries are not translated. Everything else works like a charm. When I deactivate the Hyyan WooCommerce Polylang plugin, the countries ARE translated, oddly enough. Any ideas?

I found a very old version of the site on a development machine, and the problem is not there. Somewhere with WordPress- and plugin updates the countries translation broke.

**Comment by Jon007** [comment] 2017-11-28 13:00
It works for me with WooCommerce 3.1.2 ..  and I've just tested it successfully with 3.2.5 and seems fine, even though Hyyan WooCommerce Polylang Integration: 1.0.3  does not support WooCommerce 3.2.x yet..
.. as you point out this is a standard function which works without this plugin... in principle this plugin shouldn't be affecting this, it's more likely to be triggered by some interaction with another plugin somewhere..   check your error logs as well.
Only the countries, nothing else on screen is in the wrong language?

**Comment by williamvee5** [comment] 2017-11-29 11:16
It's only the countries dropdown indeed. Thanks for the test on your systems. I'll go check the error logs and find out the conflicting plugins or code.

**Comment by Jon007** [comment] 2017-12-03 06:33
Did you find the cause?

I just thought of a few things:

- I just remembered Woo did some change to the select3 / selectwoo combo in 3.2.x  if that's any clue.
- WP 4.9 may have some impacts: Polylang 2.2.7 includes Fix queries by taxonomy broken since WP 4.9, and Polylang 2.2.6 includes 'Rework how translation files are loaded in ajax on front when the user is logged (in WP 4.7+)' which could be relevant except that you already have 2.2.6
- Also in a case like this it's useful to understand whether the effect is the same whether the user is logged in or not, and to confirm whether it what you are seeing is that the countries are always shown in the site base language, remembering that there are several languages potentially in play at any one time (site base language, user language, current post language).

**Comment by williamvee5** [comment] 2017-12-07 09:22
There's more wrong. The cart summary and the payment options on the checkout page also seem to be in the default shop language. And the thank you page as well. We're still looking into the problem.

**Comment by Jon007** [comment] 2017-12-07 09:40
>The cart summary and the payment options on the checkout page also seem to be in the default shop language.
That's a known problem introduced by woo 3.2.x where 3.2 language isn't getting applied to ajax calls.  
 it is fixed in master branch
see #251 fixes #256 and #274

**Comment by williamvee5** [comment] 2017-12-08 16:56
The master branches fixed the problem indeed. Thank you for this solution. Problems in the languages drop down remain, but we wrote a temporary fix that translates the country list based on a session variable we use to store the language. Not ideal, but it's a quick solution for now. I think it's inherited from converting WMPL to Polylang (a few years back) and the subsequent updates.

**Comment by Jon007** [comment] 2017-12-09 00:55
ok, well I think the issue should be closed then
Please feel free to open a new issue if you manage to isolate some issue related to this plugin - ideally it should be reproducible with a standard theme such as storefront.

**Closed by Jon007** 2017-12-09 00:55 UTC
