### ISSUE TITLE
Product feature image cannot be deleted / changed while Hyyan WC Polylang is active

### ISSUE THREAD

**Issue by nextab** [hyyan/woo-poly-integration#308] opened 2018-03-05 11:59 UTC
In short: We could neither remove a product thumbnail nor change it to a different image while the plugin was active. As soon as we disabled it, everything worked like a charm again.

#### What product versions and settings are you using when this issue occurs?

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.2.1
PHP post max size: |   | 200 MB
PHP time limit: |   | 30
PHP max input vars: |   | 10000
cURL version: |   | 7.35.0, OpenSSL/1.0.1f
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.38
Max upload size: |   | 200 MB

Database
--

WC database version: |   | 3.3.3
Total Database Size |   | 1.92MB
Database Data Size |   | 1.66MB
Database Index Size |   | 0.26MB

## WordPress Environment

We're currently working on a test environment. To access it the site (thygra.nextab.de), you have to enter the username "test" and the password "t3stpwd".
We're still in the setting up stage and we'll soon migrate to the live site.

WordPress environment
--
Home URL: |   | http://thygra.nextab.de
Site URL: |   | http://thygra.nextab.de
WC version: |   | 3.3.3
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 512 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | de_DE

</details>

**Comment by hyyan** [comment] 2018-03-06 08:40
@nextab could you try to disable all plugins except for woocommerce, polylang and woopoly and test again Plus please paste your plugins list and woocommerce status so I can help

**Comment by agohomer** [comment] 2018-03-07 11:09
Same issue, featured image can only be edited when the plugin is deactivated

**Comment by nextab** [comment] 2018-03-07 20:31
This is the plugin list:


Active plugins (11)
--
Polylang |   | by Frédéric Demarle – 2.3.2
Antispam Bee |   | by pluginkollektiv – 2.7.1
Duplicate Post |   | by Enrico Battocchi – 3.2.1
Custom Logo for Divi by nexTab |   | by nexTab - Oliver Gehrmann – 1.0
Hyyan WooCommerce Polylang Integration |   | by Hyyan Abo Fakher – 1.0.4 – Not tested with the active version of WooCommerce
Advanced AJAX Product Filters for WooCommerce |   | by BeRocket – 1.2.4 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway |   | by WooCommerce – 1.5.2
WooCommerce Germanized |   | by Vendidero – 1.9.9
WooCommerce |   | by Automattic – 3.3.3
WP Image Zoom |   | by SilkyPress – 1.23
WP Mail SMTP |   | by WPForms – 1.2.5



---

I did deactivate all of them except for WC, Polylang and Woopoly and everything worked then. I then re-activated the plugins 1 by 1 and backtracked the issue to the "WooCommerce PayPal Express Checkout Gateway" by WooCommerce.
As long as it was active, it wasn't possible to edit the featured images; as soon as I deactivated it, it was possible to edit the featured images again.

Hope this helps you track the issue. It's a bit surprising to see that a plugin by WooCommerce themselves is causing the conflict.

**Comment by skatana** [comment] 2018-03-10 21:21
Having the same issue that @nextab is mentioning. Featured images start working if I deactive Woopoly or WooCommerce PayPal Express Checkout Gateway.

**Comment by Jon007** [comment] 2018-03-12 06:19
duplicate of #293 "WooCommerce PayPal Express Checkout Gateway" plugin introduces admin incompatibility on product images
get them to fix it or don't use it - use the built in Paypal gateway or any of the many others which don't introduce this problem

**Comment by Marjoline** [comment] 2018-03-28 09:44
I have the problem with being unable to add featured images for any/all posts/pages/products etc. if Polylang is activated. Deactivating Polylang makes the featured image able to be added again everywhere. Even whilst Hyyan WC Polylang is active. So Hyyan is not the problem.

It is very annoying to have to disable Polylang each time a featured image needs to be added. Particularly because it means it needs to be added separately in all languages!!!  

What is the solution? Anybody?

Cheers,
Marjoline

**Comment by Jon007** [comment] 2018-03-28 10:02
@Marjoline  The solution is don’t use “WooCommerce PayPal Express Checkout Gateway” 
There are plenty of alternative Paypal gateways which don’t cause this problem.

**Closed by Jon007** 2018-03-28 10:02 UTC
