### ISSUE TITLE
Plugin doesn't work on multisite

### ISSUE THREAD

**Issue by pascalknecht** [hyyan/woo-poly-integration#210] opened 2017-07-06 11:19 UTC
First of all thanks for your plugin.

I have trouble getting your Plugin to work on Multisite. It says that I don't have Polylang 2.0 which is wrong since I have installed 2.1. I tracked the issue down to the function canActivate in the Plugin class. I found out that there are no checks in the polylangVersionCheck wheather or not the pro version is active.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0
* WordPress: 4.7.5
* WooCommerce: 3.0.5
* Polylang: 2.1
* Hyyan WooCommerce Polylang Integration: 1.0.1
* Browser: Chrome

**Comment by Jon007** [comment] 2017-07-07 14:19
this is for the same reason as #200  - the check added in 1.0.1
You can just change "src/Hyyan/WPI/Utilities.php" line 233 along the lines indicated on #200 or just comment the check out

**Comment by Jon007** [comment] 2017-07-28 01:17
re-reading this issue it appears the problem was Polylang Pro, not multisite, so closing as a duplicate of #200 which is now fixed in 1.0.2 branch

**Closed by Jon007** 2017-07-28 01:17 UTC
