### ISSUE TITLE
Unable to translate tax names, eg VAT.

### ISSUE THREAD

**Issue by henrilindeberg** [hyyan/woo-poly-integration#122] opened 2017-02-16 10:20 UTC
Unable to translate tax names, eg VAT.
Maybe this can be added to String translation?

**Comment by Jon007** [comment] 2017-04-29 07:14
Yes probably, I'm closing this as it is a duplicate of issue #59 Translate woocommerce tax name, please add any further thoughts/requirements there.

Note I have started work on #104 about the price display suffix, this would be eg '+VAT' after the price name which [soon] we will be able to translate to eg: 'mas IVA' in Spanish etc.

**Closed by Jon007** 2017-04-29 07:14 UTC
