### ISSUE TITLE
problems with variations stock above 0

### ISSUE THREAD

**Issue by elliemg** [hyyan/woo-poly-integration#425] opened 2019-05-28 09:00 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7,0,33
* WordPress: 4,9
* WooCommerce: 3,5,7
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1,3,0
* Browser: chrome

#### Steps to Reproduce
1. change stock in spanish product at 0, 
2. save
3. changes are not updated in english product

#### What I Expected
expected that stock change with the updated of product 

#### What Happened Instead
stock in variations remain the same if I set stock to 0, stock in english is not updating and remains with the last number (above 0) it has before. 
If I set stock at 1... or any number above 0 it updates, the problem is only when I set stock to 0.

## WordPress Environment

<details>

Name: Storefront Child 02
Version: 2.4.2.1551174042
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.2 – 2.5.0 está disponible
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Jon007** [comment] 2019-05-29 00:28
@elliemg  I couldn't reproduce this and I tried setting stock both to 0 and blank:
 - is Spanish the master language?
 - are all the stock options enabled under Settings, WooPoly, Metas ?
 - are you seeing the number not updating in the front end or the admin?

**Comment by elliemg** [comment] 2019-05-29 06:09
Hi, answering your questions:
- yes, Spanish is the master language
- all the stock options are enabled
- I see number not updating in front and backend

thanks for your attention

**Comment by Jon007** [comment] 2019-05-29 07:41
Stock synchronisation on save of product has always worked and I can't reproduce it on either this plugin 1.3 or the checked in version.
What does not work well in this plugin 1.3 is changes of stock when purchased - a complete fix for this will be released in version 1.4 in about 10 days time. 

more questions:

- this is when you save the product, yes?
- are you setting the stock on the individual variation or at the product level?
- the stock options are definitely enabled under both Settings, WooPoly, Features and Metas List?
- Is this a standard Variable product or are you using another product type supplied by a plugin?
- Are you able to see if the stock on the variation is updated in the database?
- What other plugins are enabled?  just to reconfirm you get this with all other plugins disabled? (apart from polylang and woocommerce)

**Comment by develgooapps** [comment] 2019-05-29 11:44
UPDATE: with the new file stock is working fine, but the price of the product does not update on the english version of the website, which gets the data from the spanish version of the website. If we change to the previous file price update right, so is this file the one messing with it now.

- this is when you save the product, yes?
Yes..

- are you setting the stock on the individual variation or at the product level?
I am setting the stock on the individual variation located on the product level, like this:
![stock](https://user-images.githubusercontent.com/37289878/58554596-ae33cd80-8217-11e9-9aa5-f28cd69e3883.PNG)

- the stock options are definitely enabled under both Settings, WooPoly, Features and Metas List?
Yes, checkbox are selected.
![yas](https://user-images.githubusercontent.com/37289878/58554635-c6a3e800-8217-11e9-8e38-bc729f42d67b.PNG)

- Is this a standard Variable product or are you using another product type supplied by a plugin?
It is a variable product.

- Are you able to see if the stock on the variation is updated in the database?
Yes.

- What other plugins are enabled? just to reconfirm you get this with all other plugins disabled? (apart from polylang and woocommerce)
Other enabled plugins are: a3 Lazy Load, Admin Menu Editor Pro, Advanced Custom Fields, All-in-One WP Migration, Booster Plus for WooCommerce, Custom Product Tabs para WooCommerce, Elementor, Elementor Pro, Facebook for WooCommerce, Hyyan WooCommerce Polylang Integration, Loco Translate, Machete, MailChimp for WordPress, Menu Icons, optimizador.io, Polylang, Post Duplicator, Really Simple SSL, Redsys WooCommerce, tipsacarrier, WooCommerce, WooCommerce added to cart popup (Ajax), WooCommerce Live Checkout Field Capture, WooCommerce Product Feed, WooCommerce QR Codes, WooCommerce Variation Swatches.

Thanks for your help.

**Comment by Portolopser** [comment] 2019-05-29 15:06
We've just sent you an invitation to see our project on GitHub

**Comment by Jon007** [comment] 2019-05-29 20:54
Hi,
- about Settings, WooPoly, Metas, your screenshot shows the Features page, the pricing and stock meta needs to be turned on, on the other tab. 
- please test with those other plugins turned off - this is one of the questions at the beginning of the ticket.

Some of those plugins definitely have the potential to interfere with the product saving process, such as:
Advanced Custom Fields
WooCommerce Variation Swatches
Booster Plus for WooCommerce
Custom Product Tabs para WooCommerce 
Elementor
WooCommerce Variation Swatches
[as far as I know some of those plugins do also have the potential to break each other as well so this looks like quite a challenging installation]

Thanks for the invitation, but I am just helping out debugging this plugin in my free time, and I don't have enough free time to do detailed debugging of other people's projects.


Anyhow, most likely another plugin is hooking the saving process and disturbing the normal sequence of events.  It would be good to know which one.
In the meantime I'll add some defensive code to stock.php for this tomorrow.

**Comment by elliemg** [comment] 2019-05-30 06:47
hi Jon, 
thank you very much for taking your time in answering :)

I understand what you mean with plugins but we deactivate every plugins leaving just woocommerce, Polylang and Hyyan actived, and it doesn't update price either... so maybe we can dismiss the compatibility with other plugins?

We really appreciate your help as we are looking at the code and don't really get how it works... :-/

**Comment by Jon007** [comment] 2019-05-30 07:32
Ok, I have verified that save on the product screen for Variable product is triggering the stock synchronisation.  This is not causing a problem in my setup but is not necessary and could potentially be causing conflict with other plugins hooking into the product save process.

I am testing some defensive code to eliminate the possibility, and will check it in within 24 hours.

**Closed** 2019-05-30 07:42 UTC
