### ISSUE TITLE
Related Products are displayed mixed in all languages

### ISSUE THREAD

**Issue by Rychetsky** [hyyan/woo-poly-integration#229] opened 2017-09-01 11:50 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8.1
* WooCommerce: 3.1.0
* Polylang: 2.2
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: All

#### Steps to Reproduce
1. Translate products
2. Translate categories
3. show related products on single product page

#### What I Expected
I expected, that the related products on the single product page are only in my active language, for example in english.

#### What Happened Instead
Related products are displays mixed in all languages. For example I get 4 random products, two in english, one in Italian and one in french.

**Comment by Jon007** [comment] 2017-09-08 10:43
What do you mean exactly by "related products"?
Is this using a shortcode?

As far as I know Upsells/Cross-sells work fine, though note if there is no translation available for any specific product they should show base language version.

And as far as the normal WooCommerce related products section goes, I've never seen any problem with that in any version of this tool:  in fact, Polylang normally intercepts all the general queries to add language filter rather than the filtering being done by this tool.

If Polylang is unable to filter, this could be because Polylang is unable to determine the language of the page.  - check the Polylang settings.

**Comment by Jon007** [comment] 2017-09-16 23:19
go to Languages, Settings /wp-admin/admin.php?page=mlang_settings and check the options for URL modifications

Valid options are:
The language is set from the directory name in pretty permalinks
Example: https://www.mysite.com/en/my-post/
The language is set from the subdomain name in pretty permalinks
Example: https://en.mysite.com/my-post/

and note that as per the readme: "Polylang URL modifications method The language is set from content is not supported yet"
If the language can't be detected from URL then language filters won't be applied by Polylang so it will be expected to see shortcode results unfiltered by language.

Closing as this is intrinsic to Polylang, not due to this plugin.

**Closed by Jon007** 2017-09-16 23:19 UTC

**Comment by abanoubsamaan** [comment] 2018-01-09 13:44
i have the same problem , mixed products in all languages are shown together instead of showing the active language products only

**Comment by smilemuffie** [comment] 2018-09-16 12:30
I have the same problem too, all languages are shown together

**Comment by AmrSubZero** [comment] 2021-01-14 04:42
Same issue! i have correct URL modifications.
if i'm on a product page it's showing the other language page of that product as a related product.
both are on product category which is also translated in two languages.

**Comment by yotamdahan** [comment] 2021-02-02 15:53
Same here

**Comment by baraaabdelhady** [comment] 2021-02-08 21:25
I have the same problem too, all languages are shown together

**Comment by Jon007** [comment] 2021-02-08 21:45
@yotamdahan @baraaabdelhady this issue is closed and cannot be reproduced on a standard installation, unless using the setting "The language is set from content" which has never been supported, cannot be supported and has always been documented as such in all the readme etc. 

If you really have a issue please open a new issue with your full details, first please trying also latest release candidate https://github.com/hyyan/woo-poly-integration/releases/tag/1.4.5
