### ISSUE TITLE
Language doesn't change completely when check out

### ISSUE THREAD

**Issue by JCcat** [hyyan/woo-poly-integration#327] opened 2018-04-16 21:39 UTC
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.27
* WordPress: 4.9.5
* WooCommerce: 3.3.5
* Polylang: 2.3.4 free ver.
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Google chrome

#### Steps to Reproduce
1. My shop has two languages, main one is Chinese and the second one is English.

2. I order a product in English page and it goes to the check out page next.

3. In English check out page, everything is in English but only the payment gateway part is still in Chinese. (including "I agree with the term" and the place order button) 
I did enter English translation for all the payment gateways in "Strings translations" from Polylang, don't know why the translation doesn't show.
    
4. Since the whole payment gateway part is in Chinese, when I click place order button (which is in Chinese), it goes to order-received page in Chinese ver. And the auto system email I got is also in Chinese.

5. One thing I did notice is when the check out page still loading, the payment gateway part is all in English. However when the page finish loading, it auto changes to Chinese language... it made me wonder if the system will auto change payment gateway by reading my IP?  

#### What I Expected
The whole check out page should be all in English, also the order-received page and system emails.

#### What Happened Instead
In check out page, the payment gateway part is in Chinese, and it leads all the rest steps becomes Chinese ver.
Please help, thank you~!

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://infurnity.com
Site URL: http://infurnity.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_TW

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 33 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.48.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔

### Post Type Counts ###

attachment: 89
custom_css: 1
customize_changeset: 11
nav_menu_item: 42
page: 46
polylang_mo: 2
post: 6
product: 6
product_variation: 20
revision: 964
shop_order: 22

### Security ###

Secure connection (HTTPS): ❌
Hide errors from visitors: ✔

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TWD (NT$)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

商店起點: #7 - /membership/
清單一覽: #8 - /cart/
付款: #9 - /checkout/
我的帳號: #10 - /myaccount/
服務條款: #1129 - /terms/

### Theme ###

Name: Modality
Version: 1.0.5.2
Author URL: http://www.vmthemes.com
Child Theme: ❌ – 
WooCommerce Support: ✔


````
</details>

**Comment by Jon007** [comment] 2018-04-17 07:02
this is a duplicate of #319 where the problem has been diagnosed and fixes are suggested

**Closed by Jon007** 2018-04-17 07:02 UTC
